icsharpcode/CodeConverter

- ICSharpCode.CodeConverter/CSharp/CompilationErrorFixer.cs
- ICSharpCode.CodeConverter/CSharp/MethodBodyVisitor.cs
- ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
- ICSharpCode.CodeConverter/CSharp/VisualBasicConverter.cs
- Tests/CSharp/ExpressionTests.cs
- Tests/CSharp/MemberTests.cs
- Tests/ConverterTestBase.cs
Fixes https://github.com/icsharpcode/CodeConverter/issues/11 and https://github.com/icsharpcode/CodeConverter/issues/12
> Qualification and out params

- ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
- ICSharpCode.CodeConverter/CSharp/NotImplementedOrRequiresSurroundingMethodDeclaration.cs
- ICSharpCode.CodeConverter/CSharp/VisualBasicConverter.cs
- ICSharpCode.CodeConverter/Util/VBUtil.cs
- Tests/CSharp/StandaloneExpressionTests.cs
- Tests/CSharp/StandaloneMultiStatementTests.cs
- Tests/ConverterTestBase.cs
- Tests/Tests.csproj
> Convert standalone expressions and improve initializer support

- ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
- ICSharpCode.CodeConverter/CSharp/TriviaConverter.cs
- ICSharpCode.CodeConverter/CSharp/VisualBasicConverter.cs
- ICSharpCode.CodeConverter/Util/SyntaxNodeExtensions.cs
- Vsix/CodeConversion.cs
- Vsix/ConvertCSToVBCommand.cs
- Vsix/ConvertVBToCSCommand.cs
- Vsix/REConverterPackage.cs
- Vsix/VSPackage.resx
- Vsix/VisualStudioInteraction.cs
- Vsix/VsDocument.cs
- Vsix/Vsix.csproj
- Vsix/app.config
- Vsix/packages.config
Addresses VB -> C# part of #9 
Also fixes #13
> VB -> C# use project context

- ICSharpCode.CodeConverter/CSharp/MethodBodyVisitor.cs
- ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
- ICSharpCode.CodeConverter/CSharp/VBToCSConversion.cs
- ICSharpCode.CodeConverter/ICSharpCode.CodeConverter.csproj
- ICSharpCode.CodeConverter/Shared/ProjectConversion.cs
- ICSharpCode.CodeConverter/Shared/TriviaConverter.cs
- ICSharpCode.CodeConverter/Util/SyntaxNodeExtensions.cs
- ICSharpCode.CodeConverter/Util/SyntaxTriviaExtensions.cs
- Tests/CSharp/MemberTests.cs
- Tests/ConverterTestBase.cs
- Vsix/CodeConversion.cs
- Vsix/ConvertCSToVBCommand.cs
- Vsix/ConvertVBToCSCommand.cs
- Vsix/source.extension.vsixmanifest
- Web/Properties/AssemblyInfo.cs
* Fixes #33
* Fixes #34
* Fixes #35
> Move conversion to another thread to avoid locking up UI

- ICSharpCode.CodeConverter/CSharp/MethodBodyVisitor.cs
- Tests/CSharp/StatementTests.cs
Avoid subtle logic changes in nested if structures
All but inner nested blocks having braces seems like a pretty sane rule to follow in most cases
I've allowed special cases for using statements and else if blocks to neaten them up
> Nested blocks

- ICSharpCode.CodeConverter/CSharp/VisualBasicConverter.cs
- ICSharpCode.CodeConverter/Util/CSharpUtil.cs
- Tests/CSharp/ExpressionTests.cs
- Tests/ConverterTestBase.cs
Support:
* Is
* IsNot
* LeftShift
* RightShift
* LeftShiftAssignment
* RightShiftAssignment
* IntegerDivide
* IntegerDivideAssignment
> VB -> C#: Expand operator support

- ICSharpCode.CodeConverter/CSharp/MethodBodyVisitor.cs
- ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
- ICSharpCode.CodeConverter/CSharp/VisualBasicConverter.cs
- ICSharpCode.CodeConverter/Util/ExpressionSyntaxExtensions.cs
- Tests/CSharp/StatementTests.cs
> VB -> C#: Improve array handling (Erase, ReDim, initializers)

- ICSharpCode.CodeConverter/VB/NodesVisitor.cs
- Tests/VB/MemberTests.cs
Fixes #83 
WIP - needs more tests and to make the test added pass
> C# -> VB: Convert expression bodies

- ICSharpCode.CodeConverter/VB/CommonConversions.cs
- Tests/VB/SpecialConversionTests.cs
> Convert Throw Expressions to multi-line lambda function

- ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
- ICSharpCode.CodeConverter/CSharp/VisualBasicConverter.cs
- ICSharpCode.CodeConverter/CodeWithOptions.cs
- Tests/CSharp/ExpressionTests.cs
- Tests/CSharp/SpecialConversionTests.cs
- Tests/ConverterTestBase.cs
Fix quote issue and improve tests
> Compile error

- ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
- Tests/CSharp/MemberTests.cs
This is a pull request with a passing test case.
> Closes #134 - Handle WithEvents fields without initializers

- ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
- ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
- ICSharpCode.CodeConverter/CSharp/QueryConverter.cs
- ICSharpCode.CodeConverter/Shared/ProjectConversion.cs
- Tests/CSharp/ExpressionTests.cs
- Tests/ProjectConverterTestBase.cs
Addresses https://github.com/icsharpcode/CodeConverter/issues/29
Reverts icsharpcode/CodeConverter#166 thus adding back #129
> VB -> C#: Improve query syntax support

- ICSharpCode.CodeConverter/CSharp/MethodBodyVisitor.cs
- ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
- Tests/CSharp/ExpressionTests.cs
- Tests/CSharp/SolutionAndProjectTests.cs
- Tests/CSharp/StatementTests.cs
- Tests/CSharp/TypeCastTests.cs
- Tests/VB/SolutionAndProjectTests.cs
> VB -> C#: Quick fixes

- .gitattributes
- CHANGELOG.md
- CodeConverter.Web/CodeConverter.Web.csproj
- ICSharpCode.CodeConverter/ICSharpCode.CodeConverter.csproj
- README.md
- Vsix/Vsix.csproj
- Vsix/source.extension.vsixmanifest
- appveyor.yml
> VS 2017 15.3

- ICSharpCode.CodeConverter/CSharp/AdditionalInitializers.cs
- ICSharpCode.CodeConverter/CSharp/ByRefParameterVisitor.cs
- ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
- ICSharpCode.CodeConverter/CSharp/MethodBodyVisitor.cs
- ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
- ICSharpCode.CodeConverter/Util/ISymbolExtensions.cs
- TestData/VBToCSCharacterization/ConvertSolution/WindowsAppVb/Form1.Designer.cs
- Tests/CSharp/ExpressionTests.cs
- Tests/CSharp/MemberTests.cs
Fixes #312 
Also makes some changes to accessibility to cater for partial classes. Will probably need future work in that area.
> Improve event handling in partial classes

- ICSharpCode.CodeConverter/Shared/Env.cs
- TestData/VBToCSCharacterization/ConvertSingleProject/EmptyVb/AClass.cs
- TestData/VBToCSCharacterization/ConvertSolution/EmptyVb/AClass.cs
- azure-pipelines.yml
Build is located at https://icsharpcode.visualstudio.com/icsharpcode-pipelines/_build?definitionId=2
Things that should be added
@GrahamTheCoder please have a look at the test failures.
> Try a minimal pipeline

- ICSharpCode.CodeConverter/CSharp/DeclarationNodeVisitor.cs
- ICSharpCode.CodeConverter/CSharp/VBToCSConversion.cs
- ICSharpCode.CodeConverter/Shared/CompilationOptionsExtensions.cs
- ICSharpCode.CodeConverter/Util/ISymbolExtensions.cs
- ICSharpCode.CodeConverter/VB/CSToVBConversion.cs
- TestData/CSToVBCharacterization/ConvertSingleProject/EmptyVb/EmptyVb.vbproj
- TestData/CSToVBCharacterization/ConvertSolution/EmptyVb/EmptyVb.vbproj
- TestData/CharacterizationTestSolution/EmptyVb/EmptyVb.vbproj
- TestData/CharacterizationTestSolution/EmptyVb/PartialClassPart.vb
- TestData/VBToCSCharacterization/ConvertSingleProject/EmptyVb/AClass.cs
- TestData/VBToCSCharacterization/ConvertSingleProject/EmptyVb/EmptyVb.csproj
- TestData/VBToCSCharacterization/ConvertSingleProject/EmptyVb/PartialClassPart.cs
- TestData/VBToCSCharacterization/ConvertSolution/EmptyVb/AClass.cs
- TestData/VBToCSCharacterization/ConvertSolution/EmptyVb/EmptyVb.csproj
- TestData/VBToCSCharacterization/ConvertSolution/EmptyVb/PartialClassPart.cs
- Tests/CSharp/ExpressionTests.cs
- Tests/CSharp/LinqExpressionTests.cs
- Tests/CSharp/MemberTests.cs
- Tests/CSharp/MissingSemanticModelInfo/ExpressionTests.cs
- Tests/CSharp/NamespaceLevelTests.cs
- Tests/CSharp/RootNamespaceTests.cs
- Tests/CSharp/SpecialConversionTests.cs
- Tests/CSharp/StandaloneStatementTests.cs
- Tests/CSharp/StatementTests.cs
- Tests/CSharp/TypeCastTests.cs
> Make ConvertText conversions partial by default

- CodeConverter.Web/CodeConverter.Web.csproj
- CodeConverter.Web/Program.cs
- CodeConverter.Web/Startup.cs
- README.md
- azure-pipelines.yml
- global.json
I reverted the merge of #382 because it was breaking the build on Azure Dev pipelines and appveyor.
> Netcore3web secondattempt

- CHANGELOG.md
- ICSharpCode.CodeConverter/VB/MethodBodyVisitor.cs
- Tests/VB/StatementTests.cs
This is a correction for #411.  
Conversion for for loop with decrementing counter (i--) was missing the "step -1"
* Turns out the token should be `MinusEquals` instead of `Minus`
> Missing for loop decrement step statement

- CHANGELOG.md
- ICSharpCode.CodeConverter/CSharp/DeclarationNodeVisitor.cs
- ICSharpCode.CodeConverter/CSharp/ExpressionNodeVisitor.cs
- ICSharpCode.CodeConverter/CSharp/MethodBodyExecutableStatementVisitor.cs
- ICSharpCode.CodeConverter/CSharp/QueryConverter.cs
- TestData/CSToVBCharacterization/ConvertSingleProject/WindowsAppVb/WindowsAppVb.vbproj
- TestData/CSToVBCharacterization/ConvertSolution/WindowsAppVb/WindowsAppVb.vbproj
- TestData/CharacterizationTestSolution/WindowsAppVb/ReferencingFormThroughStatic.vb
- TestData/CharacterizationTestSolution/WindowsAppVb/WindowsAppVb.vbproj
- TestData/SelfVerifyingTests/VBToCS/NamespaceCasing.vb
- TestData/VBToCSCharacterization/ConvertSingleProject/WindowsAppVb/WindowsAppVb.vbproj
- TestData/VBToCSCharacterization/ConvertSolution/WindowsAppVb/ReferencingFormThroughStatic.cs
- TestData/VBToCSCharacterization/ConvertSolution/WindowsAppVb/WindowsAppVb.csproj
- Tests/CSharp/LinqExpressionTests.cs
- Tests/CSharp/MemberTests.cs
- Tests/CSharp/SelfVerifyingTests.cs
- Tests/CSharp/StatementTests.cs
> Minor fixes

- CHANGELOG.md
Link to, or brief information about the issue
* Any comments on the approach taken, its consistency with surrounding code, etc.
> Add links to issues and PRs in changelog

- ICSharpCode.CodeConverter/VB/NodesVisitor.cs
- Tests/VB/TypeCastTests.cs
Just another extra parentheses
> C# -> VB: wrong parentheses around TryCast expression

- ICSharpCode.CodeConverter/VB/CommonConversions.cs
- ICSharpCode.CodeConverter/VB/MethodBodyExecutableStatementVisitor.cs
- ICSharpCode.CodeConverter/VB/NodesVisitor.cs
- Tests/VB/MemberTests.cs
- Tests/VB/StatementTests.cs
Have to return AddHandler RemoveHandler RaiseEvent code generation to custom events using field events
> C# -> VB: field events with operators += -= can appear in property events

- CodeConverter/CSharp/AdditionalInitializers.cs
- CodeConverter/CSharp/Assignment.cs
- CodeConverter/CSharp/CommonConversions.cs
- CodeConverter/CSharp/DeclarationNodeVisitor.cs
- CodeConverter/CSharp/ExpressionNodeVisitor.cs
- CodeConverter/CSharp/MethodWithHandles.cs
- CodeConverter/CSharp/MethodsWithHandles.cs
- CodeConverter/CSharp/WinformsConversions.cs
- Tests/CSharp/MemberTests/EventMemberTests.cs
- Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/WindowsAppVb/Folder/FolderForm.cs
- Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/WindowsAppVb/WinformsDesignerTest.cs
> Winforms control names

- CommandLine/CodeConv.Shared/Util/ProcessRunner.cs
After `WaitForExitAsync`, the git process has written all its output to the pipes and terminated.
However, it's possible that CodeConverter process has not yet read the data from the pipe, or that `OutputDataReceived` event is still executing after `GetExitCodeAsync()` returns.
This can cause an `ObjectDisposedException` in the `GetExitCodeAsync()` lambda expressions if the caller manages to dispose the `StringWriter` before all data is copied from the pipe to the `StringWriter`.
The `OutputDataReceived` event is called once with `e.Data == null` to signify the end-of-output. Waiting for that prevents the race condition.
> Fix race condition in GetExitCodeAsync().

- CHANGELOG.md
- CodeConverter/CSharp/BuiltInVisualBasicOperatorSubsitutions.cs
- CodeConverter/CSharp/CommonConversions.cs
- CodeConverter/CSharp/DeclarationNodeVisitor.cs
- CodeConverter/CSharp/ExpressionNodeVisitor.cs
- CodeConverter/CSharp/MethodBodyExecutableStatementVisitor.cs
- CodeConverter/CSharp/TypeConversionAnalyzer.cs
- CodeConverter/CSharp/ValidSyntaxFactory.cs
- CodeConverter/CSharp/VisualBasicEqualityComparison.cs
- Tests/CSharp/ExpressionTests/StringExpressionTests.cs
- Tests/CSharp/MissingSemanticModelInfo/ExpressionTests.cs
- Tests/CSharp/StatementTests/StatementTests.cs
- Tests/TestData/SelfVerifyingTests/VBToCS/StringEqualityTests.vb
- Tests/TestData/SelfVerifyingTests/VBToCS/StringEqualityTestsOptionCompareCaseInsensitiveText.vb
- Tests/VB/StatementTests.cs
Fixes #323
Fixes #579
Fixes #549
> VB -> CS: Select Case improvements

- CHANGELOG.md
- CodeConverter/CSharp/CommonConversions.cs
- CodeConverter/CSharp/LiteralConversions.cs
- CodeConverter/CSharp/MethodBodyExecutableStatementVisitor.cs
- CodeConverter/CSharp/TypeConversionAnalyzer.cs
- Tests/CSharp/ExpressionTests/BinaryExpressionTests.cs
- Tests/CSharp/ExpressionTests/ByRefTests.cs
- Tests/CSharp/ExpressionTests/ExpressionTests.cs
- Tests/CSharp/ExpressionTests/LinqExpressionTests.cs
- Tests/CSharp/MemberTests/PropertyMemberTests.cs
- Tests/CSharp/MissingSemanticModelInfo/ExpressionTests.cs
- Tests/CSharp/NamespaceLevelTests.cs
- Tests/CSharp/SpecialConversionTests.cs
- Tests/CSharp/StatementTests/LoopStatementTests.cs
- Tests/CSharp/StatementTests/StatementTests.cs
- Tests/CSharp/TypeCastTests.cs
- Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/VbNetStandardLib/My Project/MyNamespace.Static.2.Designer.cs
- Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/WindowsAppVb/Folder/FolderForm.Designer.cs
- Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/WindowsAppVb/WinformsDesignerTest.Designer.cs
> Arithmetic conversions

- Web/ClientApp/package-lock.json
- Web/ClientApp/package.json
- Web/ClientApp/src/components/About.tsx
- Web/ClientApp/src/components/Home.tsx
- Web/ClientApp/src/custom.css
> Monaco editor

- .github/workflows/dotnet.yml
- CommandLine/CodeConv/CodeConv.csproj
- Func/Func.csproj
- README.md
- Tests/TestData/MultiFileCharacterization/SourceFiles/ConsoleApp4/ConsoleApp4.vbproj
- Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/ConsoleApp4/ConsoleApp4.csproj
- Web/Web.csproj
- global.json
...for Web, Function and added TFM for dotnet tool
This is the minimal move to .NET 6 - see #787 (Web should be re-done & copy/pasted into new from template)
> Minimal update to .NET 6.0

- .github/workflows/dotnet.yml
- CHANGELOG.md
- CommandLine/CodeConv/CodeConv.csproj
- Directory.Build.props
- Vsix/source.extension.vsixmanifest
This seems to stop an issue resolving System.Runtime 6
https://github.com/icsharpcode/CodeConverter/issues/850#issuecomment-1065918499
> Update everything to latest for dot net core 3.1 and net 6

- CodeConverter/CSharp/CommonConversions.cs
- CodeConverter/CSharp/ValidSyntaxFactory.cs
- CodeConverter/CSharp/VisualBasicNullableExpressionsConverter.cs
- Tests/CSharp/ExpressionTests/BinaryExpressionTests.cs
- Tests/CSharp/ExpressionTests/ByRefTests.cs
- Tests/CSharp/MissingSemanticModelInfo/ExpressionTests.cs
- Tests/CSharp/StatementTests/StatementTests.cs
- Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertVbLibraryOnly/VbLibrary/My Project/MyNamespace.Static.2.Designer.cs
- Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/ConsoleApp1/My Project/MyNamespace.Static.2.Designer.cs
- Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/ConsoleApp4/My Project/MyNamespace.Static.2.Designer.cs
- Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/Prefix.VbLibrary/My Project/MyNamespace.Static.2.Designer.cs
- Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/VbLibrary/My Project/MyNamespace.Static.2.Designer.cs
- Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/VbNetStandardLib/My Project/MyNamespace.Static.2.Designer.cs
- Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/VbNetStandardLib/My Project/MyNamespace.Static.3.Designer.cs
- Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/WindowsAppVb/Folder/FolderForm.Designer.cs
- Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/WindowsAppVb/My Project/MyNamespace.Dynamic.Designer.cs
- Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/WindowsAppVb/My Project/MyNamespace.Static.1.Designer.cs
- Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/WindowsAppVb/My Project/MyNamespace.Static.2.Designer.cs
- Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/WindowsAppVb/ReferencingFormThroughStatic.cs
- Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/WindowsAppVb/WinformsDesignerTest.Designer.cs
- Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/WindowsAppVb/WinformsDesignerTest.cs
Use negated patterns for:
- nullable converter logic
- IsNot Nothing expressions
> Another area I wondered about that'd be good to get tests for: Do expressions with side-effects get executed the same?
Do you mean expressions in the context of new nullable logic? If yes then there is a bunch of tests that validate that:
https://github.com/icsharpcode/CodeConverter/blob/master/Tests/TestData/SelfVerifyingTests/VBToCS/BooleanTests.vb#L9-L43
> Use negated patterns

- CHANGELOG.md
- CodeConverter/CSharp/CommonConversions.cs
- CodeConverter/CSharp/ExpressionNodeVisitor.cs
- CodeConverter/Util/ITypeSymbolExtensions.cs
- Tests/CSharp/ExpressionTests/ByRefTests.cs
> fix wrong modifier for optional out parameter

- CHANGELOG.md
- CodeConverter/CSharp/TypeConversionAnalyzer.cs
- Tests/CSharp/TypeCastTests.cs
Fix #904 
Link to, or brief information about the issue
* Any comments on the approach taken, its consistency with surrounding code, etc.
> Fix casting object to nullable types

- CodeConverter/CSharp/CommonConversions.cs
- CodeConverter/CSharp/DeclarationNodeVisitor.cs
- CodeConverter/CSharp/MethodBodyExecutableStatementVisitor.cs
- Tests/CSharp/StatementTests/LoopStatementTests.cs
Pull loop variables only when it's needed.
> Pull loop variables only when it's needed

- CHANGELOG.md
- CodeConverter/CSharp/ExpressionNodeVisitor.cs
- Tests/CSharp/TypeCastTests.cs
- Tests/TestData/SelfVerifyingTests/VBToCS/CastTests.vb
> Fix CType conversion

- CHANGELOG.md
- CodeConverter/CSharp/ExpressionNodeVisitor.cs
- Tests/CSharp/SpecialConversionTests.cs
Fix #924 
I also fixed few issues with our changelog (9.0.2 changes were empty and two not released changes were in 9.0.1)
> Fix ChrW conversion

- Web/ClientApp/src/index.tsx
- Web/Properties/launchSettings.json
- Web/Web.csproj
I'll do other updates separately since there are more things to go wrong there
This was just to get web debuggable locally on a machine with dot net 8
> Web version updates

- CodeConverter/CSharp/CommonConversions.cs
- CodeConverter/CSharp/ValidSyntaxFactory.cs
minor improvement of #1126's code
> pass empty ParameterList instead of null
