icsharpcode/CodeConverter

ICSharpCode.CodeConverter/CSharp/MethodBodyVisitor.cs
ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
ICSharpCode.CodeConverter/CSharp/VisualBasicConverter.cs
Tests/CSharp/ExpressionTests.cs
Tests/CSharp/MemberTests.cs
Tests/CSharp/StatementTests.cs
Tests/ConverterTestBase.cs

Makes a start fixing https://github.com/icsharpcode/CodeConverter/issues/29
Also improves support for:
* Multi-dimensional array creation syntax
* Extension method syntax
* Labels and goto statements

Minimal query expression syntax, and other minor improvements

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
ICSharpCode.CodeConverter/VB/CommentConvertingNodesVisitor.cs
Tests/CSharp/ExpressionTests.cs
Tests/VB/MemberTests.cs

Should fix up specific examples from #15 and #29, though doesn't fully solve the overarching issue

Better C# -> VB attribute formatting and slight VB -> C# linq syntax improvement

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
ICSharpCode.CodeConverter/CSharp/VisualBasicConverter.cs
Tests/CSharp/ExpressionTests.cs
Tests/CSharp/NamespaceLevelTests.cs

I don't really know what I'm doing...

VbToCs: integer divide, narrowing/widening

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
ICSharpCode.CodeConverter/CSharp/VisualBasicConverter.cs
ICSharpCode.CodeConverter/VB/CSharpConverter.cs
ICSharpCode.CodeConverter/VB/NodesVisitor.cs
Tests/CSharp/MemberTests.cs
Tests/CSharp/TypeCastTests.cs
Tests/VB/MemberTests.cs

* Handle DirectCast
* VB -> C#: Convert Shadows to "new"  …
* Fix bug: New keyword should map to overloads, not shadows  …

Support VB's DirectCast, and improve Shadows keyword conversion

---

ICSharpCode.CodeConverter/CSharp/CompilationErrorFixer.cs
ICSharpCode.CodeConverter/CSharp/MethodBodyVisitor.cs
ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
ICSharpCode.CodeConverter/CSharp/VBToCSConversion.cs
ICSharpCode.CodeConverter/CSharp/VisualBasicConverter.cs
ICSharpCode.CodeConverter/Util/CSharpUtil.cs
ICSharpCode.CodeConverter/Util/INamespaceOrTypeSymbolExtensions.cs
ICSharpCode.CodeConverter/Util/ISymbolExtensions.cs
ICSharpCode.CodeConverter/Util/TypeExtensions.cs
Tests/CSharp/ExpressionTests.cs
Tests/CSharp/MemberTests.cs
Tests/CSharp/NamespaceLevelTests.cs
Tests/CSharp/SpecialConversionTests.cs
Tests/CSharp/StandaloneMultiStatementTests.cs
Tests/CSharp/StatementTests.cs
Tests/CSharp/TypeCastTests.cs
Tests/ConverterTestBase.cs
Tests/DiagnosticTestBase.cs
Tests/Tests.csproj

A very scarce set of global imports was used, and references via an alias were lost.
Also fixes #71
This is a first step in aid of #60
The scarce set of global imports was probably due to worries of cluttering the output and needing to specify all using statements for tests. This PR tidies away unused imports when there are no unresolved symbols, which covers the vast majority of the tests at least. The global imports list is now slightly expanded as a result, which should improve website conversion.

VB -> C#: Using statements and array initialization

---

ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
ICSharpCode.CodeConverter/CSharp/SyntaxKindExtensions.cs
ICSharpCode.CodeConverter/Shared/TokenContext.cs
ICSharpCode.CodeConverter/Util/SymbolExtensions.cs
ICSharpCode.CodeConverter/VB/CommonConversions.cs
ICSharpCode.CodeConverter/VB/NodesVisitor.cs
ICSharpCode.CodeConverter/VB/SyntaxKindExtensions.cs
Tests/VB/ExpressionTests.cs
Tests/VB/MemberTests.cs
Tests/VB/NamespaceLevelTests.cs
Tests/VB/SpecialConversionTests.cs
Tests/VB/StatementTests.cs

Fixes #85 
Fixes #125 
Could really do with more test cases implementing base classes and base base classes.
There's also the edge case in C# where a parent type contains the method which implements a method on an interface of a derived type which I'm not sure what to do about.
However this should be much better than it was, so worth merging I think.

C# -> VB: Interfaces "implements" clause now converted

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
Tests/CSharp/ExpressionTests.cs

There was an existing test case that showed the issue so this pull request updates that test and doesn't add any new tests.

Closes #136 - VB -> C# Use parentheses around single parameter in lambda when parameter has explicit type

---

ICSharpCode.CodeConverter/CSharp/CommonConversions.cs

Suffixes found at https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/constants-enums/constant-and-literal-data-types

VB -> C#: Add more numeric literal suffix replacements

---

ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
Tests/CSharp/MemberTests.cs

I can't think of any other members coming from a VB Module that wouldn't need the 'static' keyword added...

Closes #142 VB -> C#: Remove erroneous 'static' keyword in const field of module

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
Tests/CSharp/ExpressionTests.cs

I checked all occurrences of 'CollectionInitializer' in the [VB.NET grammar](https://docs.microsoft.com/en-us/dotnet/visual-basic/reference/language-specification/expressions) to try and make sure that there isn't any other node that a CollectionInitializer could belong to where you _wouldn't_ turn it into an implicit C# array.

Closes #139 - VB -> C#: Array literals not always converted to implicit C# array

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
Tests/CSharp/ExpressionTests.cs

In VB, properties can have indexers like this:
```vbnet
Public Property SomeProp(index As Integer) As Integer
```
When running the provided test case, VisitSimpleArgument gets an ArgumentOutOfRangeException on the call to:
```C#
parameterKinds[argId]
```
Here's why.  VisitSimpleArgument calls GetInvocationSymbol on the invocation involving SomeProperty which returns a symbol with information about that property.  The current program looks like it was mostly written with method invocation in mind so it's trying to determine if the method parameter corresponding to the argument being passed is a ref or out parameter.  In the test case, the invocation is trying to target the value _returned by_ the property (like if the value was an array or a list) as opposed to calling an indexer on the …

Closes #147 VB -> C#: Conversion error for indexer on property value of unresolved type

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
Tests/CSharp/NamespaceLevelTests.cs

The VisitQualifiedName method was prepending namespace declarations that consist of 2 or more parts (might've actually been 3 or more) with the project's root namespace.  The default root namespace that all of the tests use is "TestProject" and that gets prepended to longer namespace declarations.  Hopefully this change makes sense.  Thanks!

VB -> C#: Namespace conversion issue caused by VisitQualifiedName

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
ICSharpCode.CodeConverter/CSharp/VBToCSConversion.cs
ICSharpCode.CodeConverter/Util/EnumerableExtensions.cs
Tests/ConverterTestBase.cs

Warning, this will break almost all test cases by enclosing generated code in a namespace.  All the unit tests use an instance of VisualBasicCompilationOptions that uses .WithRootNamespace("TestProject").  Not sure if you want to just change it to use a blank root namespace or how you'd want to handle that.
Anyway, this pull request changes all of a projects generated files as follows:
- if the only member declaration is a namespace declaration, it prepends it with the VB root namespace
- otherwise all member declarations are wrapped in a new top-level namespace

#107 VB -> C#: Add VB root namespace to all converted files

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
Tests/CSharp/ExpressionTests.cs

These are the cases I could think of where it's necessary to add parens due to differences between VB and C# with operator precedence.

VB -> C#: Add parentheses where needed when convert Not, CType and TypeOf

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
Tests/CSharp/ExpressionTests.cs

I think this fixes the problem, but I don't know my way around the Roslyn type symbols too well.
EDIT:  This breaks the PartiallyQualifiedName test because the while loop I added keeps checking base classes all the way to System.Object in which case the enumerable of prefixes will contain "System".

#152 VB -> C#: Fix QualifyNode to handle inheritance

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
Tests/CSharp/StatementTests.cs

Fixes #154 
There was a compiler error when using a conditional operator in String Interpolation
* I took a look at the other code in NodeVisitor.cs, and it appears that it is common to conditionally change the return information based upon certain situations
* I am most concerned about 2 parts of this:
* `node.Parent.GetType() == typeof(VBSyntax.InterpolationSyntax)` - Is there a better way to do this?
* Location of my test. Does it belong in a better place?

vb -> C# Add parentheses around conditional expression in string interpolation

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
Tests/CSharp/ExpressionTests.cs

This pull request contains an updated test for qualifying a name that is already partially qualified as well as a code change that makes the test pass.  I'm not sure if this is the correct way to handle it.  Also, there could be some scenarios with nested classes that this doesn't handle right.

VB -> C#: Fix Qualify function to handle names that are already partially qualified

---

ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
ICSharpCode.CodeConverter/CSharp/MethodBodyVisitor.cs
ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
ICSharpCode.CodeConverter/Util/CSharpUtil.cs
ICSharpCode.CodeConverter/Util/INamespaceOrTypeSymbolExtensions.cs
ICSharpCode.CodeConverter/Util/ISymbolExtensions.cs
ICSharpCode.CodeConverter/Util/ITypeSymbolExtensions.cs
ICSharpCode.CodeConverter/Util/TypeExtensions.cs
Tests/CSharp/MemberTests.cs

In VB, an As clause isn't required for const fields or locals but in C# an explicit type is required (cannot use "var").  This fix uses the semantic model to add the explicit type when the As clause is missing.

VB -> C#: Type inferred const - convert to explicit type

---

ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
ICSharpCode.CodeConverter/CSharp/QueryConverter.cs
ICSharpCode.CodeConverter/Shared/ProjectConversion.cs
Tests/CSharp/ExpressionTests.cs
Tests/ProjectConverterTestBase.cs

https://github.com/icsharpcode/CodeConverter/issues/29
Currently don't handle several keywords, or nested statements
* First step was to handle nested statements by chunking sections together.
Which part of this PR is most in need of attention/improvement:
* The higher level methods in the `QueryConverter` are pretty much write-only code. They just batch up bits of the query for other methods to handle later, but are missing appropriate naming and probably a data structure of their own.
* The lower level methods still don't handle many cases, currently they will just throw an exception due to using `Single` in places where there can be multiple elements - I don't have examples of the more advanced cases, so I think this is fine for now, and better than barreling on missing information …

VB -> C#: Improve query syntax support

---

ICSharpCode.CodeConverter/Util/SyntaxNodeExtensions.cs

**CWE-561**. There are two '`if`' statements with identical conditional expressions. The first 'if' statement contains method return. This means that the second 'if' statement is senseless.
Replace `SingleLineCommentTrivia `-> `SingleLineDocumentationCommentTrivia`
---
And small optimization: Replace `.Count()` -> `.Length`   _O(n) vs O(1)_

Fix "if" statements

---

ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
Tests/CSharp/ExpressionTests.cs

[https://github.com/icsharpcode/CodeConverter/issues/192](https://github.com/icsharpcode/CodeConverter/issues/192)
String interpolation with a double quote fails to convert properly
* Variables were a tad inconsistent on their names vs what they represent.  Made a minor rename to make it more clear.
* How to properly clean the string for a VB -> C# conversion.  I isolated the logic around replace the double quotes and reused that functionality in case there are more edge cases to take care of there.

VB -> C# - String Interpolation With Double Quotes Not Properly Escaping Double Quotes

---

ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
ICSharpCode.CodeConverter/Util/SymbolExtensions.cs
Tests/CSharp/MemberTests.cs

[Fixes #197 ](https://github.com/icsharpcode/CodeConverter/issues/197)
WriteOnly properties on interfaces are converted incorrectly.
* Just made a minor modification to the property syntax converter to watch for the WriteOnly keyword.

Fixes #197

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
Tests/CSharp/StatementTests.cs

**VB:**
parentClass.SomeArray(2) = "sometext"
**C# (before fix):**
parentClass(2) = "sometext"
I expect: parentClass.SomeArray[2] = "sometext"

Fix array values assignment when there is a containing parent.

---

ICSharpCode.CodeConverter/CSharp/CommentConvertingMethodBodyVisitor.cs
ICSharpCode.CodeConverter/CSharp/CommentConvertingNodesVisitor.cs
ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
ICSharpCode.CodeConverter/CSharp/MethodBodyVisitor.cs
ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
ICSharpCode.CodeConverter/Util/SyntaxNodeExtensions.cs
ICSharpCode.CodeConverter/VB/CommentConvertingMethodBodyVisitor.cs
ICSharpCode.CodeConverter/VB/CommentConvertingNodesVisitor.cs
ICSharpCode.CodeConverter/VB/NodesVisitor.cs
Tests/CSharp/MemberTests.cs
Tests/CSharp/MissingSemanticModelInfo/ExpressionTests.cs
Tests/TestRunners/ConverterTestBase.cs
Tests/VB/MemberTests.cs
Tests/VB/StatementTests.cs

Fixes #241 
An error in a file that isn't within a method body causes the entire file's conversion to fail
* Convert into comment, in some cases attached to a dummy member in the VB -> C# version
Errors in VB -> C# enums will still wipe out the entire enum

Isolate errors

---

CHANGELOG.md
ICSharpCode.CodeConverter/Shared/ProjectConversion.cs
ICSharpCode.CodeConverter/VB/CommonConversions.cs
ICSharpCode.CodeConverter/VB/MethodBodyVisitor.cs
ICSharpCode.CodeConverter/VB/NodesVisitor.cs
Tests/TestRunners/ConverterTestBase.cs
Tests/VB/SpecialConversionTests.cs

* Fixes #220
The code and tests used to be tailored based on syntax alone which meant there were lots of false positives and negatives for detecting events. I've changed the code to use the semantic model to inform the conversion, and changed the tests to have valid compiling inputs/outputs.
It generally errs on the side of assuming something isn't an event, which will cause a change in behaviour "for the worse" in some cases that were specifically targeted by the old code. It's hard enough to get the right conversion when all information *is* available, so I'd rather focus on that, then make very explicit separate handling for cases of incomplete information that are *only* triggered when the semantic model comes up empty. Those cases will be prioritized based on user requests.

Raise event

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
Tests/CSharp/NamespaceLevelTests.cs

Closes #271 
When converting from VB to C#, new constraints in type parameters need to be the last constraint.
Added an OrderBy() to ensure that the new constraint ends up last. I haven't checked that the order of the other constraints remains the same, but I assume it does.

Re-order constraints when converting from VB to C#

---

ICSharpCode.CodeConverter/CSharp/MethodBodyVisitor.cs
Tests/CSharp/ExpressionTests.cs

Closes #269 
base.Finalize() is not removed when converting from VB to C#
I'm not sure this is the right/nicest way of handing this:
* I don't check that we're actually inside `~Finalize()`
* It adds an overhead for every expression statement
* I wasn't sure how to just add a comment, so there's a leading `;` in there. I decided a comment would be useful, since we're removing code - I'm happy to leave nothing there instead though.

Ensure base.Finalize() is removed

---

ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
TestData/VBToCSCharacterization/ConvertSolution/WindowsAppVb/My Project/Application.Designer.cs
Tests/CSharp/ExpressionTests.cs
Tests/CSharp/StatementTests.cs

Closes #258 
VB allows calling methods using any casing/capitalization, where C# does not. Attempt to fix the casing where possible.
* When converting identifiers, fix-up the casing
* This might be needed in other places too, but this fixes the original bug

Automatically fix the casing of identifiers where possible

---

ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
TestData/SelfVerifyingTests/VBToCS/ExpressionTests.vb
Tests/CSharp/ExpressionTests.cs
Tests/CSharp/NamespaceLevelTests.cs

Closes #260
This should implement the majority of `MyClass` support for VB -> C#. There is one case (that I'm aware of) that is missing - that should throw an exception.

Add initial support for VB MyClass expressions [#260]

---

ICSharpCode.CodeConverter/Util/SyntaxNodeExtensions.cs
Tests/CSharp/MemberTests.cs

When conversion fails, a comment is added, with code not converted. This is an incorrect translation and should cause a compilation error.
This adds a `#error`  directive before the comment to make it obvious when conversion has failed.

Add #error directive on conversion error

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
Tests/CSharp/ExpressionTests.cs

Closes #265
VB allows for parenthesis to be omitted or added for methods and properties - these need to be added or removed when converting to C#.
Added handling in two places for this:
* When we encounter `InvocationExpression` on a property
* When we encounter a lone `IdentifierName` which doesn't already have specific `()` handling
I think whitespace messed up again here, so this will probably conclict with #283.

Add/remove parenthesis as required for VB -> C#

---

ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
Tests/CSharp/ExpressionTests.cs
Tests/CSharp/StatementTests.cs

Closes #263
Visual Basic default initialises local variables, where C# does not. When translating we need to add initializers if they are not explicitly specified.
Ensure that these are initialized (if required) when converting.
I do some data flow analysis to check if we actually need to initialize the variable or not - this is not strictly required, but makes the output a little nicer.

Ensure that local variables are initialized

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
Tests/CSharp/MemberTests.cs

Closes #270 
When converting read only or write only properties in interfaces, we should not output the get or set.
Special case the output of bodiless get/set for properties in interfaces.

Do not output private get/set for interfaces

---

ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
ICSharpCode.CodeConverter/CSharp/MethodBodyVisitor.cs
ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
TestData/VBToCSCharacterization/ConvertSolution/WindowsAppVb/Form1.Designer.cs
Tests/CSharp/MemberTests.cs

Closes #103
Currently, we don't convert VB's alternative return syntax (assigning to an implicit return variable).
This adds support for assigning to the name of the method for `FunctionBlock` methods. It covers all the basic cases I can think of, I might have missed an edge case though.

Add support for VB's assign to method name return syntax

---

ICSharpCode.CodeConverter/CSharp/MethodBodyVisitor.cs
ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
Tests/CSharp/ExpressionTests.cs
Tests/CSharp/StatementTests.cs
Tests/CSharp/TypeCastTests.cs

Closes #268
When converting `CDate()`, we would previously output a cast, which causes a compile error for `CDate(String)`.
VB emits a call to `Microsoft.VisualBasic.CompilerServices.Conversions.ToDate()` - this change does the same.
I do this instead of `Convert.ToDate()`, as there are some differences in implementation which could cause different results.
`Conversions.ToDate()`: https://github.com/Microsoft/referencesource/blob/7f0c570e24e6f0084b3c5794e1a50de9fbe00ca4/Microsoft.VisualBasic/runtime/msvbalib/Helpers/Conversions.vb#L2006-L2079
`Convert.ToDate()`: https://github.com/Microsoft/referencesource/blob/3b1eaf5203992df69de44c783a3eda37d3d4cd10/mscorlib/system/convert.cs#L1712-L1790

Convert CDate() correctly

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
Tests/CSharp/ExpressionTests.cs

Closes #280 
Access to shared variables through instances is allowed in VB (though it does not evaluate the LHS).
When converting to C#, use the type name, rather than accessing through an instance.

Use class name to access shared variables

---

ICSharpCode.CodeConverter/CSharp/VBToCSConversion.cs
TestData/VBToCSCharacterization/ConvertSingleProject/EmptyVb/VisualBasicLibrary.csproj
TestData/VBToCSCharacterization/ConvertSolution/ConsoleApp1/VisualBasicConsoleApp.csproj
TestData/VBToCSCharacterization/ConvertSolution/EmptyVb/VisualBasicLibrary.csproj
TestData/VBToCSCharacterization/ConvertSolution/WindowsAppVb/WindowsAppVb.csproj

Closes #292
Converting from VB to C# uses things from the `Microsoft.VisualBasic` namespace. We need to add a reference to the assembly so this does not error.
Adds an extra bit of regex to add in the reference if it is not already there. Doesn't seem like the nicest solution, but it seems like regex is used for the rest of the `.csproj` conversion, so this is probably fine.

Add a reference to Microsoft.VisualBasic for VB -> C#

---

ICSharpCode.CodeConverter/Util/ISymbolExtensions.cs
Tests/CSharp/ExpressionTests.cs
Tests/CSharp/StatementTests.cs

Closes #261 
When converting VB to C#, built in date functions are prefixed with DateTime rather than DateAndTime.
When converting to C#, leave DateAndTime methods alone - these should be converted properly as part of #174.

Do not convert DateAndTime to DateTime

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
Tests/CSharp/ExpressionTests.cs
Tests/CSharp/StatementTests.cs

Closes #262 
Parenthesis are sometimes missing for binary expressions, causing compilation errors
Add parenthesis for binary expressions. Special case some easy examples where they are definitely not required. We would need a full precedence table to work around that.

Add parenthesis if necessary for binary expressions

---

ICSharpCode.CodeConverter/CSharp/MethodBodyVisitor.cs
Tests/CSharp/StatementTests.cs

Closes #294
Conversion currently fails for non-constant string expressions in select statements.
Explicitly handle non-constant expressions which do not result in booleans.

Add support for non-constant string select

---

ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
ICSharpCode.CodeConverter/CSharp/TypeConversionAnalyzer.cs
ICSharpCode.CodeConverter/CSharp/VBToCSConversion.cs
ICSharpCode.CodeConverter/CSharp/VisualBasicConverter.cs
TestData/SelfVerifyingTests/VBToCS/ExpressionTests.vb
Tests/CSharp/ExpressionTests.cs
Tests/CSharp/StatementTests.cs

References #267 
VB does lots of implicit conversions. We need to explicitly perform these when converting to C#.
This is a first take at this - it handles the majority of implicit conversions between primitive/"special" types that are supported in binary expressions when `Option Strict On` is set. It does not handle arguments to functions, or indicies. It doesn't handle enumerations. It is a lot more verbose than it probably needs to be - it can likely be cleaned up automatically when we add an expand/reduce pass. I opted to use `Convert.ToString(x)` rather than `x.ToString()` to handle the case where `x` is null. I hard coded a lot more of the implicit conversions than I would have liked - I did look into using `Microsoft.CodeAnalysis.CSharp.Conversion`, but it looks like you need a …

Add basic support for implicit conversions

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
Tests/CSharp/MemberTests.cs

Closes #293
Some cases were missed when handling VB's assignment return syntax.
* Ensure we look at the current node in the assignment case.
* When we have an identifier on the right hand side of an expression, replace it with the return variable, unless it is part of an invocation.

Handle more cases with VB implicit return

---

ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
ICSharpCode.CodeConverter/CSharp/SemanticModelExtensions.cs
Tests/CSharp/ExpressionTests.cs
Tests/CSharp/StatementTests.cs

Closes #297 
Variables are not initialised when convertion from C# to VB when things other than simple assignments are used.
The AlwaysAssigned dataflow analysis doesn't handle `+=`. Explicitly check for simple assignments when deciding to leave a variable uninitialised.
Unfortunately it doesn't seem like we can handle the out variable case, as the symbol info doesn't include `out` for VB - so there's a slight regression in output there.

Add more missing initialisations for VB to C#

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
Tests/CSharp/MemberTests.cs

Closes #295 
Using VB's assignment return syntax doesn't work with properties.
Use `MethodBlockBaseSyntax` instead of `MethodBlockSyntax`.

Add support for assignment return in properties

---

ICSharpCode.CodeConverter/CSharp/AdditionalLocal.cs
ICSharpCode.CodeConverter/CSharp/ByRefParameterVisitor.cs
ICSharpCode.CodeConverter/CSharp/MethodBodyVisitor.cs
ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
ICSharpCode.CodeConverter/CSharp/TypeConversionAnalyzer.cs
ICSharpCode.CodeConverter/Util/NameGenerator.cs
Tests/CSharp/ExpressionTests.cs

References #264
Add support for more complicated arguments to methods with ByRef parameters.
Takes a different approach to #204.
VB supports passing anything as a ByRef parameter, where C# requires something it can take the address of.
* When generating arguments, if the parameter is `ByRef`, create an identifier with a random name, annotate it (with `AdditionalLocal.Annotation`), and add an `AdditionalLocal`
* When visiting an expression statement, generate a sensible unique variable name, insert additional local declarations, and update the name of the argument.
* When calling a method with `ByRef` parameters in a field initializer, generate a method without `ByRef` to call instead
* We only handle the easiest of cases for field initializers - a lot of the functionality needs to overlap …

Support more complex ByRef arguments

---

ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
ICSharpCode.CodeConverter/CSharp/MethodBodyVisitor.cs
ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
ICSharpCode.CodeConverter/CSharp/SemanticModelExtensions.cs
ICSharpCode.CodeConverter/CSharp/TypeConversionAnalyzer.cs
ICSharpCode.CodeConverter/Shared/SolutionConverter.cs
ICSharpCode.CodeConverter/Util/SyntaxTokenExtensions.cs
ICSharpCode.CodeConverter/VB/NodesVisitor.cs
Tests/CSharp/ExpressionTests.cs
Tests/CSharp/NamespaceLevelTests.cs
Tests/CSharp/StatementTests.cs

Closes #180
We currently don't handle implicit enum conversions. This adds support for them
* Add support for explicit conversions in variable declarations. This is a little verbose for eg. floating point equals integer literal.
* Add support for enum -> integer conversions. This is a little verbose for eg. Binary equals. We could special case this in `VisitBinaryExpression()` to give nicer output, I opted not to do that here - happy to change it though.
* Not sure about how I got the `TypeConversionAnalyzer` into `CommonConversions` - I tried a few ways and they all seemed kinda ugly.

Enum implicit cast support

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
TestData/SelfVerifyingTests/VBToCS/ExpressionTests.vb
Tests/CSharp/ExpressionTests.cs
Tests/CSharp/MemberTests.cs
Tests/CSharp/StatementTests.cs

Closes #308
String comparison behaviour for converted VB -> C# code does not match VB's behaviour.
Added a special case for string equality. Added a special case to that to produce `string.IsNullOrEmpty()` when we can to produce slightly nicer code.

Implement correct string comparisons for VB

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
ICSharpCode.CodeConverter/CSharp/TypeConversionAnalyzer.cs
Tests/CSharp/ExpressionTests.cs

Fixes a couple of issues from previous PRs.
* Exception when `Nothing` is passed as a `ByRef` parameter
* Exception when `Integer` parameter is passed where an enum type is expected
* Handle missing case for enum conversions
* Handle lack of type info for `ByRef` parameters

Miscellaneous fixes

---

ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
ICSharpCode.CodeConverter/ICSharpCode.CodeConverter.csproj
Tests/CSharp/ExpressionTests.cs
Tests/CSharp/LinqExpressionTests.cs
Vsix/Vsix.csproj

Issue #325 is rooted in the VB.NET language model, which parses (A) array element access as (B) method invocation. Because of this, difficulty of distinguishing between A and B, and rewriting the tree accordingly falls onto converter. 
* Fixes #325
* Fixes #328
* Fixes #335 
Fix works upon existing tree rewrite mechanism of method invocation into array element access within VisitInvocationExpression routine. Logic was originally added to rewrite VB's imaginary member .Item() into array access. Issue #325 appears of similar nature. Proposed fix extends utility method  TryGetElementAccessExpressionToConvert with another expression rewrite candidate selection criteria, and lets existing rewrite logic complete the work.
* Added new test MethodCallArrayIndexerBrackets
* All tests pass, except …

fixed #325: 

---

ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
ICSharpCode.CodeConverter/CSharp/MethodBodyVisitor.cs
ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs
Tests/CSharp/MemberTests.cs

* Fixes #200 
Throws an exception for MyClass parameterized property declarations. Will wait for it to be raised as an issue if anyone ever hits the NotImplementedException.

Parameterized properties

---

CodeConverter.Web/CodeConverter.Web.csproj
CodeConverter.Web/Program.cs
CodeConverter.Web/Startup.cs

We need to migrate to 3.0 because 2.2 will EOL December 23, 2019
This is expected to not yet work on AppVeyor as the current vs2019 doesn't contain netcore3 sdk yet.

Migrate Web project to .NET Core 3.0

---

ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
Tests/CSharp/StatementTests.cs

closes issue #373 .
Current conversion uses var for declarations with multiple variables but C# issues message that multiple declaration requires an explicit type.
I made a change in SplitVariableDeclarations to requireExplicitType for the first declaration when multiple declarations are involved.
Added test `DeclarationStatementTwoVariables` to confirm correction.  Modified two affected tests after confirming they conform to the same pattern.  Changed `ForWithBlock` and `ForWithSingleStatement`

Change for issue #373. Multiple declaration with implicit type.

---

CHANGELOG.md
ICSharpCode.CodeConverter/CSharp/TypeConversionAnalyzer.cs
ICSharpCode.CodeConverter/Util/VisualBasicCompiler.cs
Tests/CSharp/MissingSemanticModelInfo/ExpressionTests.cs
Tests/CSharp/TypeCastTests.cs

Closes Issue #365 
Narrowing conversion from Object to string needed explicit ToString conversion added.
* Added System.Collections to compilation options.  In second commit.  Can do separate PR if needed.
* Changed test to var declaration in C# instead of string declaration because it appears the converter prefers the var declaration.
* Added test case for simple object to string and more complex ListArray to string array assignment.

Conversion for array index assignment

---

CHANGELOG.md
Tests/CSharp/ExpressionTests.cs

This seems to have been resolved - add a test case so it doesn't regress.
Fixes #361 
Implicit conversions in select/case statements were missed.
Already resolved - just add a test case and changelog entry.

Add test case for #361

---

CHANGELOG.md
ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
ICSharpCode.CodeConverter/CSharp/TypeConversionAnalyzer.cs
Tests/CSharp/ExpressionTests.cs

Add explicit handling for conversion of constant values, since we cannot
directly call the conversion functions at runtime.
Fixes #329
Constant values that require conversions would lead to code which fails when converted to C#.
Add explicit handling for constant values - call the relevant `Conversions.ToXXX()` method at conversion time, rather than making a runtime call. I couldn't find a Roslyn API for doing this with less code - if there is one I'd be happy to change it.

VB -> C#: Convert constant values correctly [#329]

---

CHANGELOG.md
ICSharpCode.CodeConverter/CSharp/ExpressionNodeVisitor.cs
Tests/CSharp/ExpressionTests.cs

Ensure parameterless property access short-circuit only happens when there are no parameters. This allows the existing code for `ElementAtOrDefault` to be triggered correctly.
Fixes #362
The shortcut for property access caused the `ElementAtOrDefault` handling to not trigger.
Checking the parameter length first allows this to work as expected.

VB -> C#: Fix implicit `ElementAtOrDefault` usage [#362]

---

ICSharpCode.CodeConverter/CSharp/MethodBodyExecutableStatementVisitor.cs
ICSharpCode.CodeConverter/Util/SyntaxNodeExtensions.cs
Tests/CSharp/ExpressionTests.cs

this fixes #374.
Duplicate case statements resulted in compile error
* Added warning stating the case was unreachable.  Display converted code to aid in debugging if needed.
* Instead of hard coding this message I added extensions like the `WithCsTrailingErrorComment` and `DescribeConversionError`

VB -> C#: Duplicate cases Should be Discarded

---

CHANGELOG.md
ICSharpCode.CodeConverter/CSharp/DeclarationNodeVisitor.cs
ICSharpCode.CodeConverter/CSharp/ExpressionNodeVisitor.cs
ICSharpCode.CodeConverter/CSharp/TypeConversionAnalyzer.cs
Tests/CSharp/ExpressionTests.cs

* Add explicit conversions for both branches of a ternary expression
* Add conversions for short literals
Fixes #363
Short literals in ternary expressions were not converted.
There were a couple of things here - we need to add conversions for each branch of the ternary opeartor. We could probably be more clever about this, but just adding the conversion is easy enough.
The other thing is the conversion of VB short literals. I added a case to the conversion analysis code to handle this - another (more invasive) approach would be to add an explicit case whenever we convert a VB literal that has an explicit suffix.

Convert short literals in ternary expressions [#363]

---

CHANGELOG.md
ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
ICSharpCode.CodeConverter/CSharp/DeclarationNodeVisitor.cs
Tests/CSharp/ExpressionTests.cs
Tests/CSharp/MemberTests.cs

Fixes #422
Class constructors with no modifiers in VB need to be explicitly marked as public in C#.

Ensure class constructors are marked as public [#422]

---

CHANGELOG.md
ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
ICSharpCode.CodeConverter/CSharp/DeclarationNodeVisitor.cs
ICSharpCode.CodeConverter/CSharp/ExpressionNodeVisitor.cs
TestData/SelfVerifyingTests/VBToCS/NamespaceCasing.vb
Tests/CSharp/NamespaceLevelTests.cs
Tests/CSharp/RootNamespaceTests.cs

Fixes #421
When converting multiple namespaces with the same name but different cases, the symbols from the semantic info get merged, despite being distinct symbols. Roslyn recognises this internally (using a `MergedNamespaceDeclaration`), but doesn't seem to expose it.
When this happens, `CsSyntaxGenerator` will always use the casing of the first namespace declaration it encountered, even if this is incorrect.
* When converting identifiers, only update the case if this is *not* a declaration
* When getting a `TypeSyntax` for conversion, manually replace the identifiers when the strings are identical, but cases don't match.
The tests for this will fail until #414 is merged. I didn't want to include it in there, since it's already doing quite a lot, and my solution to this seems rather …

Ensure casing matches for namespaces [#421]

---

CHANGELOG.md
ICSharpCode.CodeConverter/CSharp/ExpressionNodeVisitor.cs
ICSharpCode.CodeConverter/CSharp/LambdaConverter.cs
ICSharpCode.CodeConverter/CSharp/MethodBodyExecutableStatementVisitor.cs
ICSharpCode.CodeConverter/CSharp/TypeConversionAnalyzer.cs
TestData/SelfVerifyingTests/VBToCS/BooleanTests.vb
TestData/SelfVerifyingTests/VBToCS/EnumTests.vb
Tests/CSharp/MemberTests.cs
Tests/CSharp/StatementTests.cs

Object initializers, nullables and awaits

---

ICSharpCode.CodeConverter/VB/NodesVisitor.cs
Tests/VB/MemberTests.cs

fix conversion of custom event with backing field
https://github.com/icsharpcode/CodeConverter/issues/435

c# -> vb custom event improvements

---

ICSharpCode.CodeConverter/VB/CommonConversions.cs
ICSharpCode.CodeConverter/VB/NodesVisitor.cs
ICSharpCode.CodeConverter/VB/SyntaxKindExtensions.cs
Tests/TestRunners/ConverterTestBase.cs
Tests/VB/MemberTests.cs
Tests/VB/NamespaceLevelTests.cs

https://github.com/icsharpcode/CodeConverter/issues/451
https://github.com/icsharpcode/CodeConverter/issues/454
https://github.com/icsharpcode/CodeConverter/issues/455
1. [generic static classes are converted into modules, which can't be generic](https://github.com/icsharpcode/CodeConverter/issues/451)
2.  [Generic interfaces has wrong Implements statement without type parameters](https://github.com/icsharpcode/CodeConverter/issues/454)
3. [Inner namespaces are moving to root Imports clause as is, but in some cases its should merged with parent namespace](https://github.com/icsharpcode/CodeConverter/issues/455)

C# -> VB: don't convert generic static to module, fix generic interface implements statement, concatenate inner namespaces with the parent

---

ICSharpCode.CodeConverter/VB/NodesVisitor.cs
Tests/VB/ExpressionTests.cs

ugly CSharpImpl.__Assign() in converted code
replace
(x = AssignX())
in expression:
x ?? (x = AssignX())
with:
Function
x = AssignX()
Return x
EndFunction

C# -> VB: Improve CoalesceExpression conversion

---

CHANGELOG.md
ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
ICSharpCode.CodeConverter/CSharp/ExpressionNodeVisitor.cs
ICSharpCode.CodeConverter/Util/CSharpUtil.cs
ICSharpCode.CodeConverter/Util/NameGenerator.cs
ICSharpCode.CodeConverter/VB/CSToVBProjectContentsConverter.cs
ICSharpCode.CodeConverter/VB/CSharpConverter.cs
ICSharpCode.CodeConverter/VB/CaseConflictResolver.cs
ICSharpCode.CodeConverter/VB/CommonConversions.cs
Tests/VB/MemberTests.cs
Tests/VB/SpecialConversionTests.cs

In VB identifiers' names are case insensitive. There is
compilation error, when a property have the same name as a field or a local variable
rename fields and local variables if needed with "_" at begin

C# -> VB: rename fields and local variables in simple case

---

CHANGELOG.md
ICSharpCode.CodeConverter/VB/CommonConversions.cs
ICSharpCode.CodeConverter/VB/NodesVisitor.cs
Tests/VB/ExpressionTests.cs
Tests/VB/TypeCastTests.cs

Parentheses around CType expression lead to compilation error
((Test)o).TestMethod(); ->  (CType(o, Test)).TestMethod()

C# -> VB: Remove extra parentheses around CType expression

---

ICSharpCode.CodeConverter/VB/CommonConversions.cs
ICSharpCode.CodeConverter/VB/NodesVisitor.cs
Tests/VB/NamespaceLevelTests.cs

Compile errors after conversion for some aliases, like:
Imports DbModelBuilder = Global.Microsoft.EntityFrameworkCore.ModelBuilder;
I can't reproduce the problem using simple test
remove GlobalNameSyntax from QualifiedNameSyntax in Imports

C# -> VB: remove global overqualification for type's aliases

---

ICSharpCode.CodeConverter/VB/CommonConversions.cs

GlobalNameSyntax contains in the last leaf of QualifiedNameSyntax's nodes tree.
Simplier reduces erroneous Global syntax in Imports. So, the issue doesn't covered by the GlobalImportsStatement test. Simplifier fails on some code files, while code are compiling and properly running.

C# -> VB: Global qualification problem

---

CHANGELOG.md
ICSharpCode.CodeConverter/VB/CommonConversions.cs
ICSharpCode.CodeConverter/VB/NodesVisitor.cs
Tests/VB/MemberTests.cs

correct shared modifier for backing fields, created via conversion of static inferred properties

C# -> VB: shared modifier for backing fields

---

ICSharpCode.CodeConverter/CSharp/CommonConversions.cs
ICSharpCode.CodeConverter/CSharp/DeclarationNodeVisitor.cs
ICSharpCode.CodeConverter/VB/CommonConversions.cs
Tests/CSharp/MemberTests.cs
Tests/CSharp/NamespaceLevelTests.cs

Fixes #528
I have found a problem, which is very likely the cause of #528. The compiler's semantic model doesn't list the event as handled by the method. This may be a bug, or a subtlety in the API.
I've got a workaround for this but it's causing some comment related test failures which needs investigating

Get the events from syntax that have been optimized away

---

CodeConverter/CSharp/ExpressionNodeVisitor.cs
Tests/CSharp/ExpressionTests/ExpressionTests.cs

Fixes #626 
In some cases the null coalesce operator is missing parenthesis, resulting in incorrect output.
* The same mechanism is used as already exists for the ternary operator
* Covered by test `NullCoalescingOperatorUsesParenthesisWhenNeededAsync`

VB -> C#: Add brackets for null coalesce operator when needed

---

CommandLine/CodeConv.Shared/CodeConvProgram.cs

The command line converter only currently takes absolute paths, and crashes if a relative path is supplied.
Check if the path is rooted & that the file does not exist.
If so, try combining with the current directory.

Fix: Crash if relative path supplied to command line

---

CHANGELOG.md
CodeConverter/CSharp/VBToCSConversion.cs
CodeConverter/VB/CSToVBConversion.cs
Tests/TestData/MultiFileCharacterization/CSToVBResults/ConvertCSharpConsoleAppOnly/ConsoleApp2/CSharpConsoleApp.vbproj
Tests/TestData/MultiFileCharacterization/CSToVBResults/ConvertWholeSolution/ConsoleApp2/CSharpConsoleApp.vbproj
Tests/TestData/MultiFileCharacterization/SourceFiles/ConsoleApp2/CSharpConsoleApp.csproj
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertVbLibraryOnly/VbLibrary/VbLibrary.csproj
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/VbLibrary/VbLibrary.csproj
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/WindowsAppVb/WindowsAppVb.csproj

This closes #641 
The documentation file path is different between C# projects and VB projects. In C# it includes the output directory path. In VB the output path is separate.
* Added tweakOutputPath to CStoVBConversion  and VBtoCSConversion class which is called from PostTransformProjectFile method.
* Updated MultiFileSolutionAndProjectTests to test and verify the Documentation File tag results.

Output path updates for project Files

---

CHANGELOG.md
CodeConverter/VB/NodesVisitor.cs
CodeConverter/VB/SyntaxKindExtensions.cs
Tests/VB/MemberTests.cs

Closes #659 
Missing visitor for explicit/implicit conversion operators
* mapped Explicit to narrowing conversion and implicit to widening conversion in new ConversionOperatorDeclaration visitor.
* test mirrors the VB -> C# conversion/tests

Add vistor for ConversionOperatorDeclaration

---

CodeConverter/VB/MethodBodyExecutableStatementVisitor.cs
CodeConverter/VB/NodesVisitor.cs
Tests/VB/StatementTests.cs

there is no CallStatementSyntax for ObjectCreationExpression when several expressions are used. For example
new TaskFactory() as TaskFactory)
.StartNew(() => { })
.ContinueWith(t => {});

CS -> VB: improve generation of Call statement

---

Tests/Tests.csproj

This closes #674. 
After installing .NET 5.0 the MultiFileSolutionAndProjectTests were failing. 
* Updated package references for Microsoft.Build and Microsoft.Build.Tasks.Core for the test project to 16.8 (from 16.4)

Resolve Multi-file Solution and Project test failures after install .Net 5.0

---

CodeConverter/CSharp/ExpressionNodeVisitor.cs
CodeConverter/CSharp/LiteralConversions.cs
CodeConverter/VB/NodesVisitor.cs
Tests/CSharp/ExpressionTests/StringExpressionTests.cs
Tests/VB/ExpressionTests.cs

This closes issue #684 . 
For format text on interpolated strings require an escape for the "\" character in C#, but not in VB. 
* Added code to add an extra"\" converted to C# and to remove the unneeded "\" converting to VB.
* The test converting to VB is failing.  Would like pointer on getting it to pass. C# needs `using System;` but VB doesn't but the test says "comments for line 0 not converted." Without `using System;` the conversion is unsuccessful.

Add code for format clause escape character.

---

CHANGELOG.md
CodeConverter/Util/CSharpUtil.cs
CodeConverter/VB/CommonConversions.cs
Tests/VB/ExpressionTests.cs

This closes issue #682 .
The system is generating a local variable for an out parameter. The type symbol was incorrectly parsed as a VB type which didn't properly recognize generics.
* I replaced the call to `ToVBSyntax` with a call to the C# SyntaxFactory.ParseText instead of VB ParseText for the type symbol which then recognized the generic and the needed type arguments. I also added a call to the node visitor on the resulting CS type syntax.
* The ToVBSyntax had a NULL check (for type Symbol returned from `ExtractBestMatch<ITypeSymbol>`. Unsure if an explicit  NULL check and error throwing is needed
* Resharper formatted ExpressionsTest.cs resulting in several "minor" changes to the file. I can undo if needed.
* I did need to add the …

Updated ConvertToVariableDeclarator to handle generic declarations

---

CodeConverter/CSharp/LambdaConverter.cs
Tests/CSharp/ExpressionTests/ExpressionTests.cs

This closes #657 
anonymous Async function without parameters was missing the async in converted code.
* Added a check to see if anonymous function is Async like the other 2 lamba conversions
* I'm unsure if the else is needed (lines 56-61) there isn't a test that covers those lines, but since the other two routines check for anonymous I left it in. I think all lambas should be anonymous

VB -> C#: add async check for lamba expressions

---

CodeConverter/CSharp/VisualBasicEqualityComparison.cs
Tests/CSharp/ExpressionTests/StringExpressionTests.cs

This closes #689 .
For proper runtime behavior string variable = nothing should use string.IsNullOrEmpty 
* Simple update to the Linq expression to use string compare

update string = nothing expression to use IsNullOrEmpty

---

CHANGELOG.md
CodeConverter/VB/CommonConversions.cs
Tests/VB/SpecialConversionTests.cs

closes issue #695 
Hex literals for unsigned integers or large integers require a suffix in VB. Was missing in conversion.
* Add check for literal type and add suffix if needed

handle U32/U64 hex literals without suffix

---

CodeConverter/CSharp/DeclarationNodeVisitor.cs
Tests/CSharp/MemberTests/EventMemberTests.cs

https://github.com/icsharpcode/CodeConverter/issues/701
* When 'Handles' identifier is on new line, it gets prefixed with a bunch of whitespace. i.e.
```
Button2
```
* So after getting this identifier from syntax tree / library calls, trim it before escaping and using.

Trim whitespace from event source identifiers. Fixes #701

---

.github/workflows/dotnet.yml

I have not matched https://github.com/icsharpcode/CodeConverter/blob/master/azure-pipelines.yml#L57 (necessary???)
First run artifacts:
https://github.com/icsharpcode/CodeConverter/actions/runs/586676519#artifacts
Note that GH re-zips automatically for download (no way around this behavior) and that artifacts can be downloaded only when you are logged in to GH.
Build passing badge can be built for master/succeeded once merged. TODO after merge: delete azure-pipelines.yml & pipeline on Azure DevOps.
Please squash-merge.

Build GH Action Build matching Azure DevOps Pipeline

---

Web/ClientApp/package-lock.json
Web/ClientApp/package.json

This resolves #724 
Monaco editor didn't display string with backslash in it properly 
```
Dim x = "n:\filepath\"
DriveStatus.DTest()
```
Displayed DriveStatus.Dtest() in red as if it was still part of the string.
* Did npm upgrade on client app project to do a non-breaking upgrade on dependencies upgraded the following dependencies
- monaco-editor/react 3.6.3 to 3.8.3
- axios 0.20.0 to 0.20.1
- bootstrap 4.1.3 to 4.6.0
- react 16.13.1 to 16.14.0
- react-dom 16.13.1 to 16.14.0
- react-scripts 3.4.3 to 3.4.4
- react-strap 8.4.1 to 8.9.0
- ajv 6.12.4 to 6.12.6
- eslint-plugin-import 2.22.0 to 2.23.4
- eslint-plugin-jsx-a11y 6.3.1 to 6.4.1
- eslint-plugin-react 7.24.0
- typescript 3.9.7 to 3.9.9
- 
* Did manual test in local web server verified display looks good …

bump dependency version & audit fixes to resolve #724 web display issue.

---

CodeConverter/CSharp/CommonConversions.cs
CodeConverter/CSharp/DeclarationNodeVisitor.cs
CodeConverter/CSharp/ITypeContext.cs
CodeConverter/CSharp/TypeContext.cs
CodeConverter/CSharp/VBToCSConversion.cs
CodeConverter/CSharp/VBToCSProjectContentsConverter.cs
CodeConverter/CSharp/VisualBasicConverter.cs
CodeConverter/ILanguageConversion.cs
CodeConverter/Shared/ProjectConversion.cs
CodeConverter/Shared/SolutionConverter.cs
CodeConverter/VB/CSToVBConversion.cs
CommandLine/CodeConv.Shared/MSBuildWorkspaceConverter.cs
Tests/CSharp/MultiFileSolutionAndProjectTests.cs
Tests/TestData/MultiFileCharacterization/SourceFiles/VbLibrary/Module1.vb
Tests/TestData/MultiFileCharacterization/SourceFiles/VbLibrary/VbLibrary.vbproj
Tests/TestData/MultiFileCharacterization/SourceFiles/VbNetStandardLib/AnInterface.vb
Tests/TestData/MultiFileCharacterization/SourceFiles/VbNetStandardLib/AnInterfaceImplementation.vb
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertVbLibraryOnly/VbLibrary/Module1.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertVbLibraryOnly/VbLibrary/VbLibrary.csproj
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/VbLibrary/Module1.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/VbLibrary/VbLibrary.csproj
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/VbNetStandardLib/AnInterface.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/VbNetStandardLib/AnInterfaceImplementation.cs
Tests/TestRunners/ConverterTestBase.cs
Tests/Tests.csproj
Vsix/CodeConversion.cs

https://github.com/icsharpcode/CodeConverter/issues/731
When the interface and the implementation are in the assembly that is not being converted the converter takes the property/method name from the interface instead of the concrete class. 
As the result, the code doesn't compile.
Check if the type is not in the assembly being converted and then take the property name from the appriopate symbol (interface or implementation).
It probably doesn't cover the case when we convert a single document.

VB -> C#: Converter takes the property name from interface instead of the concrete class.

---

.github/workflows/dotnet.yml
CHANGELOG.md
CodeConverter/CodeConverter.csproj
CommandLine/CodeConv.NetFramework/CodeConv.NetFramework.csproj
CommandLine/CodeConv/CodeConv.csproj
Func/Func.csproj
Vsix/OutputWindow.cs
Vsix/Vsix.csproj
Vsix/source.extension.vsixmanifest
Web/Web.csproj

The build tools update commit seemed to be required locally in VS2022 in order to avoid a complicated SDK error regarding the bitness of the task (which was presumably x86-only until 16.9 when the team realized they were going 64 bit soon).

Allow 2022 installation

---

Vsix/Vsix.csproj

Entirely removing PIA ref as per https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/migrated-assemblies?view=vs-2022 see issue #760

Experiment for issue #760

---

CodeConverter/CSharp/DeclarationNodeVisitor.cs
Tests/CSharp/ExpressionTests/ParameterTests.cs

Fixes an invalid cast exception when converting optional parameters from VB to C#

Fixes an issue where Visual Basic optional parameter fails conversion to C#

---

.github/workflows/dotnet.yml

Update the version in its new location so it affects all assemblies
Note: Still doesn't update the VSIX version like IncrementVersion.ps1 does - could always adapt that file or use its Regex if we wanted to go the whole way

Update version for all assemblies

---

CHANGELOG.md
CodeConverter/CSharp/MethodBodyExecutableStatementVisitor.cs
CodeConverter/CSharp/PerScopeState.cs
Tests/CSharp/MemberTests/MemberTests.cs

[See comment on #623](https://github.com/icsharpcode/CodeConverter/issues/623#issuecomment-1009917188)
When there is no initializer, and also no default initializer is generated because the value is always assigned before the first read, an NRE is thrown because the field generation assumes there always is an initializer.
* The field is now generated without an initializer in that case.
* Alternatively, the field could be entirely omitted and the VB Static keyword ignored, because the value is always overwritten anyways, but this way it is closer to the original VB code.

Fix NRE when a VB static variable has no initializer

---

CodeConverter/CSharp/ExpressionNodeVisitor.cs
Tests/CSharp/ExpressionTests/XmlExpressionTests.cs

Fixes #253
* The current implementation does not handle embedded expressions well
Also, there are some other minor problems surrounding XML:
* XDocument is assigned using XElement instead (leading to compile error)
* Self-Closing tags are converted incorrectly
* Conditional access (?.) on XML expression throws ArgumentNullException during conversion
* Use a per-member visiting approach to construct an actual expression instead of calling XElement.Parse() at runtime (I think that is much closer to what VB actually does)
* Use XDocument constructor in VisitXmlDocument
* Implement VisitXmlEmptyElement to correctly convert self-closing tags
* Use MemberBindingExpression in VisitXmlMemberAccessExpression when node.Base is null (such is the case for conditional access)
The new approach may …

Use new XElement(...) instead of XElement.Parse(...)  for conversions of XML expressions from VB to C#

---

CHANGELOG.md
CodeConverter/CSharp/DeclarationNodeVisitor.cs
CodeConverter/Util/SyntaxTokenExtensions.cs
Tests/CSharp/ExpressionTests/ByRefTests.cs
Tests/CSharp/MemberTests/MemberTests.cs

Fixes #819. Ignore whitespaces when reviewing - I had to remove one big indentation.
1. I noticed that there is a problem with ```RemoveOnly``` method. The name suggests that it will remove all modifiers that are matching the predicate but in reality, it was removing modifiers only if exactly one match was found in the list.
It wasn't working correctly for methods with ```protected internal``` because two modifiers were matched so nothing was removed.
You can see this behavior in the converted code for ```IFoo.ExplicitProperty``` in #819.
2. Method ```IsPrivateInterfaceImplementation``` was renamed to ```IsNonPublicInterfaceImplementation``` and the condition was changed so any non-public interface implementation returns true.
3. Allowed generating delegating members not only for …

Fix access modifiers for explicit interface implementations.

---

CodeConverter/CSharp/DeclarationNodeVisitor.cs
CodeConverter/CSharp/HandledEventsAnalysis.cs
CodeConverter/Util/SyntaxTokenExtensions.cs

1. Renamed ```RemoveOnly``` to ```RenameWhere```
2. Simplify namespaces
3. Removed ```interfaceMemberIdentifiers``` variable. It was populated but never used.

Small code cleanup for Property/MethodStatement visitors

---

CHANGELOG.md
CodeConverter/CSharp/CommonConversions.cs
CodeConverter/CSharp/DeclarationNodeVisitor.cs
CodeConverter/CSharp/ExpressionNodeVisitor.cs
Tests/CSharp/ExpressionTests/ByRefTests.cs
Tests/CSharp/MemberTests/IndexerTests.cs
Tests/CSharp/MemberTests/MemberTests.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/VbNetStandardLib/AnInterfaceImplementation.cs
Tests/TestData/SelfVerifyingTests/VBToCS/InheritanceTests.vb
Tests/TestData/SelfVerifyingTests/VBToCS/NamespaceCasing.vb
Tests/TestData/SelfVerifyingTests/VBToCS/ParametrizedPropertiesInheritanceTests.vb
Tests/TestData/SelfVerifyingTests/VBToCS/ShadowsInheritanceTests.vb

Fixes #813 
Reworked explicit interface implementations for properties/parametrized properties and methods.
Now all explicit implementations have a delegate call to the implementation.
This simplifies the generated code (no casting is required) and fixes some issues like:
- Having a renamed implementation that is abstract. The old solution would generate delegating calls for abstract members which is not correct.
- ReadOnly/WriteOnly explicit interface implementations would have getter/setter which doesn't compile.
- Having a virtual implementation that is being overridden later by a child class. The old solution could change the logic.
- Having one property that implements two interfaces and there is a naming difference only in the second member e.g.:
`Property A As Integer Implements …

Fix explicit interface implementations

---

CHANGELOG.md
CodeConverter/CSharp/MethodBodyExecutableStatementVisitor.cs
Tests/CSharp/ExpressionTests/ExpressionTests.cs
Tests/CSharp/StatementTests/StatementTests.cs

Fixes #432 (or at least most common scenarios).
1. Consider Throw/Break/Return/Continue as keywords that will exit from ```case```.
2. Check if the previous ```if``` statement will exit on all code paths.
I'm not sure if there is some kind of built-in way in Roslyn to check it. My solution will cover only simple ifs. Nested switch/if statements will still generate ```break``` keyword.

Remove redundant  break expressions in switch-case statements. 

---

CodeConverter/CSharp/MethodBodyExecutableStatementVisitor.cs
Tests/CSharp/MemberTests/MemberTests.cs

The part that extracts the member name which is used as part of the generated field name was not prepared for the case where the static local is inside a property, throwing a NotImplementedException.
* Implemented the missing case, extracting the name from the parent PropertyBlock

Fix NotImplementedException when converting property with VB Static local

---

CodeConverter/CSharp/HandledEventsAnalyzer.cs
Tests/VB/CaseSensitivityTests.cs

#854 
When the property declaration and the property reference in the Handles clause, differ by case, the conversion fails trying to create two event containers.
* Pass the semantic model to CreateEventContainer so it can be used to get the name from the property declaration
* Change is relatively minor, all unit test continue to pass
* Added new unit test, unit test fails without change, passes after change.
* Copied "hasLineCommentConversionIssue: true /*Fields re-ordered*/);" from another test, not sure what that actually means.

Issue #854: Fix conversion error when Handle clause property differs by case from actual property

---

CodeConverter/CSharp/ExpressionNodeVisitor.cs
Tests/CSharp/ExpressionTests/ByRefTests.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertVbLibraryOnly/VbLibrary/AClass.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertVbLibraryOnly/VbLibrary/Module1.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/Prefix.VbLibrary/AClass.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/Prefix.VbLibrary/Module1.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/VbLibrary/AClass.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/VbLibrary/Module1.cs

Add post-assignment to hoisted by-ref argument when argument is an identifer, member access, or array access. Fixes #856
https://github.com/icsharpcode/CodeConverter/issues/856
https://github.com/icsharpcode/CodeConverter/issues/856
* Return PreAndPostAssignment when expression is a candidate for inline passing if not for the type mismatch.
* All other cases (such as when expression is NothingLiteralSyntax, ObjectCreationSyntax, etc) still just return PreAssignment as before.

Add post-assignment to hoisted by-ref argument

---

CHANGELOG.md
CodeConverter/CSharp/ExpressionNodeVisitor.cs
CodeConverter/Util/FromRoslyn/ITypeSymbolExtensions.cs
Tests/CSharp/TypeCastTests.cs

Ideally, I would just call ```Conversions.ToInteger``` when we cast strings to enums but it looks like VB.Net does some magic for fractional types as well.

use explicit cast when integral numeric types are casted to enum

---

CHANGELOG.md
CodeConverter/CSharp/DeclarationNodeVisitor.cs
CodeConverter/CSharp/ExpressionNodeVisitor.cs
CodeConverter/CSharp/TypeConversionAnalyzer.cs
CodeConverter/CSharp/VbSyntaxNodeExtensions.cs
CodeConverter/CSharp/VisualBasicNullableExpressionsConverter.cs
CodeConverter/CodeConverter.csproj
Tests/CSharp/ExpressionTests/BinaryExpressionTests.cs
Tests/TestData/SelfVerifyingTests/VBToCS/BooleanTests.vb
Tests/TestData/SelfVerifyingTests/VBToCS/NullableRelationalOperators.vb
Vsix/Vsix.csproj

Fixes #840 
I finally found some time to put all pieces together and create a PR.
Few things to note:
1. I had to update roslyn version to ```3.4.0``` so I can use recursive patterns. I guess it would mean end of support for VS2017? 
Is converter still supporting it?
https://docs.microsoft.com/en-us/visualstudio/extensibility/roslyn-version-support?view=vs-2022
BTW I noticed that some projects are already using ```3.4.0``` version but CodeConverter project was referencing ```2.8.2```
2. I couldn't force ```x is {} a``` to format nicely. Roslyn was creating something very ugly:
```csharp
x is 
{
} a
```
I tried to play with removing trivia etc but it didn't work. The only solution I found was to use ```Parse``` method. Look at ```NotFormattedIsPattern```.
3. The code it generates is …

Fix binary expressions for nullable types in VB->C# conversion

---

CHANGELOG.md
CodeConverter/CSharp/VisualBasicEqualityComparison.cs
Tests/CSharp/ExpressionTests/ExpressionTests.cs

Use string.IsNullOrEmpty when comparing string to string.Empty

---

CHANGELOG.md
CodeConverter/CSharp/DeclarationNodeVisitor.cs
CodeConverter/CSharp/ExpressionNodeVisitor.cs
CodeConverter/CSharp/TypeConversionAnalyzer.cs
CodeConverter/CSharp/ValidSyntaxFactory.cs
CodeConverter/CSharp/VisualBasicNullableExpressionsConverter.cs
CodeConverter/CodeConverter.csproj
CodeConverter/Util/FromRoslyn/ConversionExtensions.cs
CodeConverter/Util/FromRoslyn/ITypeSymbolExtensions.cs
CodeConverter/Util/FromRoslyn/VbConversionKind.cs
Tests/CSharp/ExpressionTests/BinaryExpressionTests.cs
Tests/CSharp/StatementTests/StatementTests.cs
Tests/CSharp/TypeCastTests.cs
Tests/TestConstants.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertVbLibraryOnly/VbLibrary/My Project/MyNamespace.Static.2.Designer.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertVbLibraryOnly/VbLibrary/My Project/Settings.Designer.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/ConsoleApp1/My Project/MyNamespace.Static.2.Designer.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/ConsoleApp1/My Project/Settings.Designer.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/ConsoleApp4/My Project/MyNamespace.Static.2.Designer.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/Prefix.VbLibrary/My Project/MyNamespace.Static.2.Designer.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/Prefix.VbLibrary/My Project/Settings.Designer.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/VbLibrary/My Project/MyNamespace.Static.2.Designer.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/VbLibrary/My Project/Settings.Designer.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/VbNetStandardLib/My Project/MyNamespace.Static.3.Designer.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/WindowsAppVb/Folder/FolderForm.Designer.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/WindowsAppVb/My Project/MyNamespace.Static.2.Designer.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/WindowsAppVb/My Project/Settings.Designer.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/WindowsAppVb/WinformsDesignerTest.Designer.cs

Fixes #865 
It fixes most problems with casts around integrals/fractional/enum types including nullables.

Fix invalid call to Conversions.ToInteger for nullable types

---

CHANGELOG.md
CodeConverter/CSharp/TypeConversionAnalyzer.cs
Tests/CSharp/StatementTests/StatementTests.cs
Tests/CSharp/TypeCastTests.cs
Tests/TestData/SelfVerifyingTests/VBToCS/EnumTests.vb

Fixes #888 
BTW I wanted to write some more advanced self-verifying tests for the conversion logic but found out that their Compilation object has errors: missing xunit references.
Because of that, the logic in ```TryAnalyzeCsConversion``` is not triggered. ```csConvertedType``` is null (for some reason Roslyn doesn't see C# view of vb types in our case).
https://github.com/icsharpcode/CodeConverter/blob/1f81cc89ea9024b472c07ece067c5dc0c53fc562/CodeConverter/CSharp/TypeConversionAnalyzer.cs#L166-L172
The fix is easy but maybe it's intended to test how non-compiling code is converting?

Fix enum conversions

---

CodeConverter/CSharp/XmlImportContext.cs
Tests/CSharp/ExpressionTests/XmlExpressionTests.cs
Tests/TestData/SelfVerifyingTests/VBToCS/XmlTests.vb

These changes to the boilerplate template fix run-time errors in some special cases:
- Generating an XDocument with imported XML namespaces: This used to throw an Exception because the xmlns attributes cannot be added to the Document itself. Add to the root instead.
- Make Apply idempotent by including the main element in the scan for duplicate attributes, so that no "Duplicate Attribute" error can occur, even when Apply happens to be called twice on the same element.
- Add readonly attribute to make linter happy

Bugfixes for XML Import Helper code

---

CHANGELOG.md
CodeConverter/CSharp/TypeConversionAnalyzer.cs
Tests/CSharp/TypeCastTests.cs
Tests/TestData/SelfVerifyingTests/VBToCS/CastTests.vb

[ VB -> C#: wrong conversion of generic function with CType #893](https://github.com/icsharpcode/CodeConverter/issues/893)
When casting to a generic type in VB, the converted C# code can fail at runtime where VB doesn't.
`return (T)resultObj;     // run time error when T is short`
* Use Call to `Microsoft.VisualBasic.CompilerServices.ToGenericParameter<>` instead of simple cast

fix for VB -> C#: wrong conversion of generic function with CType #893

---

CodeConverter/CSharp/ExpressionNodeVisitor.cs
Tests/CSharp/ExpressionTests/XmlExpressionTests.cs

This is another incremental improvement to the conversion of XML literals. The Namespace prefixes `xml:` and `xmlns:` are special, in that they don't need to be explicitly imported. A common use case is the `xml:lang` attribute, for which a test has been added. Formerly this led to an error at runtime, because just specifying `"xml:lang"` as the attribute name does not work, since `:` is not a valid character for an attribute name.
Instead, when converting XNames using these prefixes, the constants from XNamespace are now used. To achieve this, the handling of XNames has been applied to attributes as well. Care has been taken, and an existing test has been extended, to ensure that default xml namespaces don't get added to attributes, as per …

Add support for builtin xml namespaces

---

CodeConverter/CSharp/HoistedDefaultInitializedLoopVariable.cs
CodeConverter/CSharp/MethodBodyExecutableStatementVisitor.cs
CodeConverter/CSharp/PerScopeState.cs
Tests/CSharp/StatementTests/LoopStatementTests.cs
Tests/TestData/SelfVerifyingTests/VBToCS/VariableScopeTests.vb

[Link to issue this covers](https://github.com/icsharpcode/CodeConverter/issues/897)
Uninitialized variables are implicitly set to the default value in VB. The converter needs to add the initialization explicitly. However, in VB the initialization only happens once, even when the variable declaration is inside a loop. Therefore the converted code behaves differently.
* Pull default initialized variables out of the loop to ensure they are only initialized once.
* This also applies to nested loops: variables are pulled all the way out to ensure the same behavior as in VB.
* Nested loops in VB can lead to different variables with the same name that end up in the same scope after conversion. These have their names changed.

Fix Issue #897 (VB -> C#: variable is initialized inside loop)

---

CodeConverter/CSharp/QueryConverter.cs
Tests/CSharp/ExpressionTests/LinqExpressionTests.cs
Tests/TestData/SelfVerifyingTests/VBToCS/LinqExpressionTests.vb
Tests/TestData/SelfVerifyingTests/VBToCS/VariableScopeTests.vb

[Link to issue(s) this covers](https://github.com/icsharpcode/CodeConverter/issues/895)
Nested clauses after a group by get dropped, also the wrong default selection is used.
* Pass along the nested clauses to CreateGroupByContinuation, so they no longer get lost.
* When building a "group by" continuation, do not use the selection from the nested clause if it is the default selection, select the group itself instead.

Fix Issue #895 (VB -> C#: missing where and wrong select in linq with group clause)

---

CHANGELOG.md
CodeConverter/CSharp/ExpressionNodeVisitor.cs
CodeConverter/Util/SymbolExtensions.cs
Tests/CSharp/ExpressionTests/ExpressionTests.cs
Tests/CSharp/ExpressionTests/ParameterTests.cs
Tests/CSharp/MemberTests/PropertyMemberTests.cs
Tests/TestData/SelfVerifyingTests/VBToCS/OmittedArgumentsTests.vb

Fixes #906 
More complicated than I initially thought. The idea of just providing every omitted argument didn't work for all cases. Example:
Input [sharplab.io](https://sharplab.io/#v2:DYLgbgRgNAJiDUAfAkgWwA4HsBOAXAzgAQDKAnvrgKaoCwAUPQAoCuEwAlgMaEDCwAhviIA1dvmb9gAIUFc+g/E1YduxVoQCyACn6EAgkWK5s7AHYBzAJT1Ct3plP5MwSgDoA6iaoAZM5S0AJABEAN78AL5B1nQAoqYwJKxKbFyJEJo6+obGZuZQhOmChBQmFtF29o7Obp7sPn6BoRGEIRCR0XEJahDJKmkZAPLouOwOkoS6BiQ5FoQAvIRBAIxB+UMjY8AFE0QlufOLAEyrhJjDo6bj3EV7swtBAMxRNnY8Dk4uHl6Uvqb+wWFwi02i1OO16J00vReqluoQAErMUxacq2bTLFb5IKHY5QVEZfggOYYk4deJQ2Lk+RCIA===):
```vbnet
Public Sub M(a As String)
Console.WriteLine($"{a}")
End Sub
Public Sub M(a As String, b as string)
Console.WriteLine($"{a} {b}")
End Sub
Public Sub M(Optional a As String = "1", Optional b as string = "2", optional c …
```

Fix converting Omitted/Optional parameters which could result in wrong method overload being called.

---

CHANGELOG.md
CodeConverter/CSharp/MethodBodyExecutableStatementVisitor.cs
Tests/CSharp/StatementTests/LoopStatementTests.cs
Tests/TestData/SelfVerifyingTests/VBToCS/VariableScopeTests.vb

Fixes #911 
You can explicitly initialize variables with default values. In these cases, the declarations shouldn't be pulled before the loop.
* Any comments on the approach taken, its consistency with surrounding code, etc.

Fix variable declaration incorrectly pulled before the loop

---

CHANGELOG.md
CodeConverter/Common/LineTriviaMapper.cs
CodeConverter/Common/ProjectConversion.cs
CodeConverter/Util/SyntaxNodeExtensions.cs
Tests/CSharp/TriviaTests.cs

Fix #917 
> You'd probably need to change them to be converted before going into the collection for consistency.
@GrahamTheCoder I'm not sure if I understand this correctly. What do you mean by "change trivia to be converted for consistency"? Isn't the error trivia already created in target language?

Fix mapping for error trivia added by converter

---

.github/workflows/dotnet.yml

Part of https://github.com/icsharpcode/CodeConverter/issues/795
Irritatingly the action I'm using only runs on ubuntu so it has to be a totally separate job. IIRC we need to build on windows for some legacy msbuild related stuff to work
TODO
`if: ${{ github.ref == 'refs/heads/master' }}`
@christophwille You'll need to setup the repo settings something like this:

Push to github pages

---

CodeConverter/CodeConverter.cs
Func/Convert.cs
Func/Func.csproj
Func/GlobalSuppressions.cs
Func/Startup.cs
Func/host.json
Func/local.settings.json
Web/WebConverter.cs

As an extension, I'd like to suggest passing ILoggerFactory? into the call chain so we can create logger instances (when non-null) to log errors and information (that can be surfaced in case of the Azure Functions deployment using Application Insights).

Pass CancellationToken

---

CodeConverter/CSharp/VBToCSConversion.cs
CodeConverter/Common/OptionalOperations.cs
CodeConverter/VB/CSToVBConversion.cs

#877
A deeply nested single expression seemed to cause this issue. 
Currently just skips simplification when it takes longer than the configurable timeout. This at least allows the conversion to proceed.
* Try adding new lines
* Try extracting sub expressions into their own field
* Even simplifying with the simplify annotation only on the namespace node takes 48.5s
* All the time seems to be in GetOriginalSymbol info. I believe that for each identifier, it essentially rebinds the entire expression in order to get the original symbol.
* Very similar sort of issue here: https://lightrun.com/answers/omnisharp-omnisharp-vscode-omnisharp-gets-stuck-at-100-cpu-when-analyzing-complex-automapper-profiles

Apply timeout to simplification

---

Vsix/Vsix.csproj
Vsix/source.extension.vsixmanifest

Potentially fixes #989 
This should make the extension installable on VS2022 on arm. I don't have a device to test it with, and even if it installs it may not work. Any feedback would be appreciated
[ICSharpCode.CodeConverter.VsExtension.zip](https://github.com/icsharpcode/CodeConverter/files/10962282/ICSharpCode.CodeConverter.VsExtension.zip)

Enable arm64 vsix

---

CodeConverter/CSharp/MethodBodyExecutableStatementVisitor.cs
CodeConverter/CSharp/PerScopeState.cs
CodeConverter/Common/NameGenerator.cs
Tests/CSharp/StatementTests/LoopStatementTests.cs

See PR #902 for the explanation of the root issue. Issues #998 and #1000 are bugs in #902 in two specific cases.
The fix for the two issues is in the same location `PerScopeState.CreateLocalsAsync()`
* For #998
Renaming the original variable with a unique ID as we go up the tree should only be done (and is only needed) in the nested loops case.
* For #1000 
Renaming the original variable in case of conflict was only done in the nested loops case, but a conflict can also happen in the non-nested case (see test).
A side effect of the fix is that the renaming occurs only in case of conflict (see modified test for the nested loops case).
* I have tried to merge the nested and non-nested code paths, but currently I don't think it is possible.

Fix Issue #998 and #1000

---

CodeConverter/CSharp/VBToCSConversion.cs
CodeConverter/Common/ProjectFileTextEditor.cs
CodeConverter/VB/CSToVBConversion.cs
Tests/LanguageAgnostic/ProjectFileTextEditorTests.cs
Tests/LanguageAgnostic/SolutionFileTextEditorTests.cs
Tests/TestData/MultiFileCharacterization/CSToVBResults/ConvertWholeSolution/CSharpNetStandardLib/CSharpNetStandardLib.vbproj
Tests/TestData/MultiFileCharacterization/CSToVBResults/ConvertWholeSolution/NetCore/NetCore.vbproj
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertVbLibraryOnly/VbLibrary/VbLibrary.csproj
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/ConsoleApp1/VisualBasicConsoleApp.csproj
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/ConsoleApp4/ConsoleApp4.csproj
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/Prefix.VbLibrary/Prefix.VbLibrary.csproj
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/VbLibrary/VbLibrary.csproj
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/VbNetStandardLib/VbNetStandardLib.csproj
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/WindowsAppVb/WindowsAppVb.csproj
Tests/TestRunners/MultiFileTestFixture.cs

See issue #1003
For the VB to CS project file conversion, `<DefineDebug>` and `<DefineTrace>` should be converted to `<DefineConstants>`.
* I've used `XDocument` to parse and edit the XML (this is already used elsewhere in the codebase, e.g. to parse the resource files).
* I've also done a similar job in the neighborhood for consistency and to simplify the code (especially in the case of the `<DocumentationFile>` conversion).
* The main change in external behavior (aside from fixing the issue) is that the `XDocument` step can cause minor changes in formatting (this can be seen in the updated test files), but I don't think this is an issue (they are new files generated by the converter, not existing files).
* I've done a small change in `MultiFileTestFixture` to ouput the expected file …

Fix issue #1003

---

CHANGELOG.md
CodeConverter/CSharp/DeclarationNodeVisitor.cs
CodeConverter/CSharp/ExpressionNodeVisitor.cs
CodeConverter/CSharp/MethodBodyExecutableStatementVisitor.cs
Tests/CSharp/StatementTests/OnErrorStatementTests.cs

Partial (simplest possible case) fix for https://github.com/icsharpcode/CodeConverter/issues/426
Simplest case covered here: A single top level On Error Go To, everything after it could be placed in a try catch and go to the outer label
* OnErrorGoTo statement and label in same scope, but not top-level (e.g. nested in an if statment/loop)
* Extend that system to two statements within a scope (e.g. changing the error handler part way through, it would be possible to have a nested try catch block for the second one, and use an filter clause to avoid hitting the outer one
General solution: The difficulty is that in C# the labels are scoped to the containing block, so it isn't possible to goto a label straight from a catch block. I've therefore created a loop and switch to allow it to …

OnError GoTo

---

.github/workflows/dotnet.yml

https://github.com/roryprimrose/set-vs-sdk-project-version/issues/20 @v1 does not roll up automatically to latest revision.

Specifically use 1.0.6 action that is using node 16

---

CHANGELOG.md
CodeConverter/CSharp/ClashingMemberRenamer.cs
Tests/CSharp/MemberTests/MemberTests.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertVbLibraryOnly/VbLibrary/AClass.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertVbLibraryOnly/VbLibrary/AnEnum.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/Prefix.VbLibrary/AClass.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/Prefix.VbLibrary/AnEnum.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/VbLibrary/AClass.cs
Tests/TestData/MultiFileCharacterization/VBToCSResults/ConvertWholeSolution/VbLibrary/AnEnum.cs

Fixes #1035 
* Any comments on the approach taken, its consistency with surrounding code, etc.
// few tests are failing, will take a look at them later...

fix: ClashingMemberRenamer incorrectly renames Enum types

---

CHANGELOG.md
CodeConverter/CSharp/CommonConversions.cs
CodeConverter/CSharp/DeclarationNodeVisitor.cs
CodeConverter/CSharp/ExpressionNodeVisitor.cs
CodeConverter/CSharp/MethodBodyExecutableStatementVisitor.cs
CodeConverter/CSharp/PerScopeState.cs
CodeConverter/Common/NameGenerator.cs
CodeConverter/Common/SymbolRenamer.cs
CodeConverter/VB/NodesVisitor.cs
Tests/CSharp/ExpressionTests/ExpressionTests.cs

Overescape identifiers

---

CodeConverter/CSharp/DeclarationNodeVisitor.cs
Tests/CSharp/MemberTests/MemberTests.cs

Fixes #1109
"Default visibility on Declared members isn't adjusted"
Get modifiers in a similar manner to how `MethodStatementSyntax` is analyzed (use `GetMemberContext(node)`).

use `TokenContext` when creating modifiers for a `DeclareStatementSyntax`

---

CodeConverter/CSharp/LiteralConversions.cs
CodeConverter/Common/DocumentExtensions.cs
Tests/CSharp/SpecialConversionTests.cs

#1064
For `&H80040E19` we get `int.MinValue + 0x00040E19`. With this PR, we'd get `unchecked((int)0x80040E19)` instead, thus preserving the hex literal value.
Corresponding code in LiteralConversion.cs was adjusted.
Additionally, I had to change `CsWouldBeSimplifiedIncorrectly` to return true for `CastExpressionSyntax` with `Parent` that's a `CheckedExpressionSyntax`, because otherwise it would've caused CS0266: "Cannot implicitly convert type 'uint' to 'int'".
Note this rule is a bit too aggressive:
```cs
int i = unchecked(0x80040E19); //we prevent error CS0266 here
uint u = unchecked(0x80040E19); //but we also prevent this from happening
```
(and many more cases with different types)
I'm reasonable sure it doesn't matter though: this PR introduces the very first call to …

generate `unchecked((int)0x91234567)` instead of `int.MinValue + 0x11234567`

---

CodeConverter/CSharp/ExpressionNodeVisitor.cs
Tests/CSharp/MemberTests/MemberTests.cs

#1106: ByRef temporary variable is assigned back into a constant
* Only a minor change in `GetRefConversion`

Always use `RefConversion.PreAssigment` for `const`s

---

CodeConverter/CSharp/CommonConversions.cs
CodeConverter/CSharp/ExpressionNodeVisitor.cs
CodeConverter/CSharp/KnownNamedTypes.cs
CodeConverter/CSharp/MethodBodyExecutableStatementVisitor.cs
Tests/CSharp/MemberTests/MemberTests.cs

#1048: Interop method invocations with OptionalAttribute aren't converted
* *Any comments on the approach taken, its consistency with surrounding code, etc.*
I decided to leave compiler errors in code, so that `BC30455: Argument not specified for parameter...` becomes `CS7036: There is no argument given that corresponds to the required formal parameter...`.
* *Which part of this PR is most in need of attention/improvement?*
1. I couldn't quite achieve above goal: VB.NET doesn't respect the `Optional` parameter (because it doesn't need to, I guess), so we have 3 compiler errors in the VB.NET code instead of 1 should we reference a C# assembly. This means the output generated looses some compiler errors -- I'm not quite sure if that's ok. We'd need to setup two different projects to have a …

take parameter attributes into account in `CreateOptionalRefArg`

---

CodeConverter/CSharp/ExpressionNodeVisitor.cs
Tests/CSharp/MemberTests/MemberTests.cs

#1107: OmittedArgumentSyntax isn't converted into temporary variable for ByRef parameters causing error CS7036
* Only a minor change. I decided to have redundand call to `processedParameters.Add(parameterSymbol.Name);` in these cases (by removing the just added name), to keep the number of `if`s (and avoid nesting another one within). There are alternatives, but IMHO the tiny performance impact is ok.

Convert explicitely omitted ByRef arguments into temporary variables

---

CodeConverter/CSharp/ExpressionNodeVisitor.cs
CodeConverter/CSharp/HoistedFieldFromVbStaticVariable.cs
CodeConverter/CSharp/MethodBodyExecutableStatementVisitor.cs
CodeConverter/CSharp/PerScopeState.cs
CodeConverter/Common/AnnotationConstants.cs
CodeConverter/Util/SyntaxNodeExtensions.cs
Tests/CSharp/MemberTests/MemberTests.cs

#1054: Statics with same name in getter and setter cause a CONVERSION ERROR
* _Any comments on the approach taken, its consistency with surrounding code, etc._
The solution is basically to store accessor kind in every `IdentifierNameSyntax` of a static, and to use that value later when doing the renaming.
* _Which part of this PR is most in need of attention/improvement?_
Currently, it creates `_Prop_b` and `_Prop_b1`, which is fine, but it would be nicer to get `_Prop_Get_b` and `_Prop_Set_b` instead. This is easy to achieve if *every* static from a property would get that infix. It's a bit more cumbersome if only those with duplicate name would get one.

Differentiate between statics in setters and getters

---

CodeConverter/CSharp/ExpressionNodeVisitor.cs
Tests/CSharp/MemberTests/MemberTests.cs

ByRef argument w/o parentheses is treated like a writable variable, even if it's a method:
```vb
Sub S(ByRef i as Object)
M(GetI)
End Sub
Function GetI() As Integer : End Function
```
becomes
```cs
public bool M(ref object i)
{
object argi1 = GetI();
M(ref argi1);
GetI() = argi1; //compiler error
}
public int GetI()
{
return default;
}
```
* _Any comments on the approach taken, its consistency with surrounding code, etc._
The adjustment itself is very minor: return `RefConversion.PreAssigment` from `GetRefConversion` when the symbol is an `IMethodSymbol`.
* _Which part of this PR is most in need of attention/improvement?_
I've excluded `ReturnsByRef == false && ReturnsByRefReadonly == false`, same as with properties. This generates code like this atm:
```cs
object argi2 = …
```

Don't write back into a method call when it's ByRef argument

---

CodeConverter/CSharp/ExpressionNodeVisitor.cs
CodeConverter/CSharp/MethodBodyExecutableStatementVisitor.cs
CodeConverter/CSharp/VisualBasicEqualityComparison.cs
Tests/CSharp/ExpressionTests/ExpressionTests.cs

#1100: `Select Case [object]` can have incorrect converted code
* _Any comments on the approach taken, its consistency with surrounding code, etc._
`GetFullExpressionForVbObjectComparison` now has a `ComparisonKind` parameter (new enum).
`VisitSelectBlock` now checks if expression type is object first, in which case  different code is generated.
* _Which part of this PR is most in need of attention/improvement?_
* `ComparisonKind` has `Unknown` value, which might not be necessary - I added it in case something goes terribly wrong.
* `ComparisonAdjustedForStringComparison()` (renamed from `EqualsAdjustedForStringComparison()`) has `return SyntaxFactory.BinaryExpression(GetSyntaxKind(comparisonKind), csLeft, csRight);` for the non-Object case. With how the code currently looks like, the …

convert `Select Case [object]` using `Operators.ConditionalCompareObject...`

---

CodeConverter/Util/CSharpUtil.cs

#1146 
Using the test RelationalOperatorsOnNullableTypeInConditionAsync for demonstration
During the debugging session:
For vb node (with nullable variable) at the begining of ConvertBinaryExpressionAsync method :
x = y
C# code at the end of the method:
Before:
ParenthesizedExpressionSyntax ParenthesizedExpression ((((((((x))).HasValue)&&((((y))).HasValue)))&&((((((x))).Value)==((((y))).Value)))))
After:
ParenthesizedExpressionSyntax ParenthesizedExpression ((((x).HasValue)&&((y).HasValue))&&(((x).Value)==((y).Value)))
In AddParens, only add parenthesis if it is not already a ParenthesizedExpressionSyntax
This eliminate a lot of unneeded parenthesis
This is a modification to the current AddParens method. It seems to have only one definition of such method. But the …

AddParens only if it is not already a ParenthesizedExpressionSyntax

---

CodeConverter/CSharp/LiteralConversions.cs
Tests/CSharp/SpecialConversionTests.cs

https://github.com/icsharpcode/CodeConverter/issues/1147 (Edit: Issue is duplicate of reopened https://github.com/icsharpcode/CodeConverter/issues/754)
Hex literals of numeric types uint, ulong and long with larger values than int.MaxValue failed to convert as there was a special case for int hex literals, where the numeric value is parsed to an int causing a wrong conversion.
Restricting this special case (8 digit hex literal) to values of type int only.
https://github.com/icsharpcode/CodeConverter/issues/1115 resolved issue https://github.com/icsharpcode/CodeConverter/issues/1064 for integer values but long hex literals (16 digit hex literal) seem to have the same issue:
0xFFFFFFFFFFFFFFFEL is interpreted as uint64 instead of int64.
So this PR also applies the same solution to convert
` …

Fixed conversion of large uint/ulong/long hex literals

---

CodeConverter/Util/FromRoslyn/IMethodSymbolExtensions.cs
Tests/CSharp/ExpressionTests/ExpressionTests.cs

https://github.com/icsharpcode/CodeConverter/issues/1148
AddressOf delegates are wrapped in lambdas when delegate signatures are not equal but still compatible.
This behaviour is implemented correctly for base and derived classes but not for interfaces.
Using InheritsFromOrEquals overload with the option to include interfaces for delegates that widen the return type to an interface that is implemented by the type or narrow the input parameters types to classes implementing the interface.

AddressOf does not wrap compatible signatures in lambdas anymore

---

Tests/TestRunners/ConverterTestBase.cs

#1145 
By setting DefaultThreadCurrentUICulture to CultureInfo.InvariantCulture, in the base class of the unit tests, it ensure that the asserted build error text and actual error text will be in the same language

Set the DefaultThreadCurrentUICulture to a specific culture, asserted error language consistency

---

CodeConverter/CSharp/TypeConversionAnalyzer.cs
Tests/CSharp/TypeCastTests.cs

Issue 1159 inferred generic integer type cast
